# =============================================
# SIMF - Clean Publish All Web Apps
# Cleans old output, publishes sequentially, stops on first error.
#
# Publishes the four SIMF web apps into publish\api, publish\cp, publish\web and
# publish\edge. Those folder names are the contract deploy\iis-deploy.ps1
# expects, so the output can be deployed straight away:
#
#   .\publish.ps1
#   .\deploy\iis-deploy.ps1 -ArtifactRoot .\publish `
#       -ApiSiteName  "SIMF.API"  -ApiPath  "D:\System\v1.0.1\api" `
#       -CpSiteName   "SIMF.CP"   -CpPath   "D:\System\v1.0.1\cp"  `
#       -WebSiteName  "SIMF.WEB"  -WebPath  "D:\System\v1.0.1\web" `
#       -EdgeSiteName "SIMF.EDGE" -EdgePath "D:\System\v1.0.1\edge"
#
# Notes:
# - There is no separate Worker project: the 10 background workers run
#   IN-PROCESS inside the API application pool (see deploy\README.md). One
#   instance is elected to run them by WorkerLease, so API x4 does not send
#   every reminder four times.
# - The mobile edge is included here because a handover or manual release built
#   from this script IS the package that gets installed. It used to build three
#   apps while the pipeline built four, so a hand-built package silently had no
#   edge and api.simrsnf.com had nothing to answer it.
# - This script builds and publishes ONLY. It sets no configuration and no
#   secrets - those are Machine-scope environment variables applied on the
#   server by deploy\set-env.ps1 (SIMF-OPS-001 section 6).
# - web.config is generated by `dotnet publish` for Web SDK projects.
# =============================================

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$publishBase = Join-Path $root "publish"
$config = "Release"

# Project -> output folder mapping (publishable web apps only, in deploy order).
$projects = @(
    @{ Name = "API";          Csproj = "src\Backend\SIMF.Api\SIMF.Api.csproj";                         Folder = "api"  },
    @{ Name = "ControlPanel"; Csproj = "src\ControlPanel\SIMF.ControlPanel\SIMF.ControlPanel.csproj";  Folder = "cp"   },
    @{ Name = "Website";      Csproj = "src\Website\SIMF.Web\SIMF.Web.csproj";                         Folder = "web"  },
    @{ Name = "MobileEdge";   Csproj = "src\Edge\SIMF.MobileEdge\SIMF.MobileEdge.csproj";              Folder = "edge" }
)

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  SIMF - Publish All ($config)"          -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Step 1: Clean old publish output
Write-Host "[1/4] Cleaning old publish folders..." -ForegroundColor Yellow
foreach ($p in $projects) {
    $outDir = Join-Path $publishBase $p.Folder
    if (Test-Path $outDir) {
        Remove-Item $outDir -Recurse -Force
        Write-Host ("  Removed: " + $p.Folder) -ForegroundColor DarkGray
    }
}
Write-Host "  Done." -ForegroundColor Green
Write-Host ""

# Step 2: Clean build caches (bin/obj) to prevent stale DLLs
Write-Host "[2/4] Cleaning build caches..." -ForegroundColor Yellow
foreach ($p in $projects) {
    $csprojPath = Join-Path $root $p.Csproj
    dotnet clean $csprojPath --configuration $config --verbosity quiet 2>$null
    Write-Host ("  Cleaned: " + $p.Name) -ForegroundColor DarkGray
}
Write-Host "  Done." -ForegroundColor Green
Write-Host ""

# Step 3: Restore packages
Write-Host "[3/4] Restoring packages..." -ForegroundColor Yellow
foreach ($p in $projects) {
    $csprojPath = Join-Path $root $p.Csproj
    dotnet restore $csprojPath --verbosity quiet 2>$null
}
Write-Host "  Done." -ForegroundColor Green
Write-Host ""

# Step 4: Publish each project sequentially
Write-Host "[4/4] Publishing projects..." -ForegroundColor Yellow
Write-Host ""

$total = $projects.Count
$current = 0
$failed = $false

foreach ($p in $projects) {
    $current++
    $csprojPath = Join-Path $root $p.Csproj
    $outDir = Join-Path $publishBase $p.Folder
    $label = "  [$current/$total] " + $p.Name + " -> " + $p.Folder

    Write-Host $label -ForegroundColor White

    $sw = [System.Diagnostics.Stopwatch]::StartNew()

    dotnet publish $csprojPath --configuration $config --output $outDir 2>&1 | Out-Null

    $exitCode = $LASTEXITCODE
    $sw.Stop()
    $elapsed = [math]::Round($sw.Elapsed.TotalSeconds, 1)

    if ($exitCode -ne 0) {
        Write-Host "  FAILED!" -ForegroundColor Red
        Write-Host ""
        Write-Host "========================================" -ForegroundColor Red
        Write-Host ("  PUBLISH FAILED: " + $p.Name)           -ForegroundColor Red
        Write-Host ("  Exit code: " + $exitCode)               -ForegroundColor Red
        Write-Host "========================================" -ForegroundColor Red
        Write-Host ""
        Write-Host "Re-running with verbose output:" -ForegroundColor Yellow
        Write-Host ""

        dotnet publish $csprojPath --configuration $config --output $outDir

        $failed = $true
        break
    }

    Write-Host ("  OK (" + $elapsed + "s)") -ForegroundColor Green
}

Write-Host ""

if (-not $failed) {
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "  ALL PROJECTS PUBLISHED SUCCESSFULLY"    -ForegroundColor Green
    Write-Host ("  Output: " + $publishBase)              -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green

    # Show folder sizes
    Write-Host ""
    foreach ($p in $projects) {
        $outDir = Join-Path $publishBase $p.Folder
        if (Test-Path $outDir) {
            $sizeBytes = (Get-ChildItem $outDir -Recurse | Measure-Object -Property Length -Sum).Sum
            $sizeMB = [math]::Round($sizeBytes / 1MB, 1)
            Write-Host ("  " + $p.Folder.PadRight(15) + " " + $sizeMB + " MB") -ForegroundColor DarkGray
        }
    }
}

Write-Host ""
