// Tests: SIMF.Api.Tests/YoutubeTranscriptServiceTests.cs
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using SIMF.Application.Programme.Abstractions;
using SIMF.Common;

namespace SIMF.Infrastructure.Programme;

/// <summary>
/// D-578 — server-side YouTube caption fetch. Resolves the video id via the shared
/// <see cref="LiveStreamUrlPolicy"/>, lists the caption tracks through YouTube's public
/// "innertube" player API (the ANDROID client bypasses the web consent interstitial),
/// downloads the chosen track as JSON3 and flattens it to running text.
///
/// <para><b>Fragile by nature + network-gated:</b> the innertube/timedtext endpoints are
/// undocumented and can change without notice, and the RSNF/NCA on-prem network blocks
/// YouTube egress — so every failure funnels to a single clear
/// <c>SUBTITLE_FETCH_FAILED</c> (502) that tells the admin to paste/upload instead. It
/// reuses the process-wide singleton <see cref="HttpClient"/> (the Infrastructure csproj
/// does not reference <c>Microsoft.Extensions.Http</c>; adding it needs owner approval —
/// CLAUDE.md §1.7), exactly like the AI providers.</para>
/// </summary>
internal sealed class YoutubeTranscriptService(
    HttpClient httpClient,
    ILogger<YoutubeTranscriptService> logger) : IYoutubeTranscriptService
{
    // The public YouTube web "innertube" API key — shipped in every browser's
    // youtube.com page, NOT a secret. Authorises the player endpoint that lists a
    // video's caption tracks.
    private const string InnertubeKey = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8";

    private const string PlayerUrl =
        "https://youtubei.googleapis.com/youtubei/v1/player?key=" + InnertubeKey;

    public async Task<TranscriptResult> FetchAsync(
        string videoUrl, string? preferredLang, CancellationToken cancellationToken = default)
    {
        if (!LiveStreamUrlPolicy.TryGetYouTubeVideoId(videoUrl, out var videoId))
        {
            throw new ApiException(
                ErrorCodes.SubtitleFetchFailed, 400,
                "The link is not a recognised YouTube video URL.",
                "الرابط ليس رابط فيديو YouTube صالحًا.");
        }

        var tracks = await ListCaptionTracksAsync(videoId, cancellationToken);
        if (tracks.Count == 0)
        {
            throw new ApiException(
                ErrorCodes.SubtitleFetchFailed, 422,
                "This video has no captions to import — paste or upload the subtitle instead.",
                "لا تتوفّر ترجمة لهذا الفيديو — الصق النص أو ارفع ملف الترجمة بدلاً من ذلك.");
        }

        var track = ChooseTrack(tracks, preferredLang);
        var text = await DownloadTranscriptAsync(track.BaseUrl, cancellationToken);
        if (string.IsNullOrWhiteSpace(text))
        {
            throw new ApiException(
                ErrorCodes.SubtitleFetchFailed, 502,
                "The caption track could not be read.",
                "تعذّرت قراءة ملف الترجمة.");
        }

        return new TranscriptResult(text, track.LanguageCode, track.AutoGenerated);
    }

    private async Task<IReadOnlyList<CaptionTrack>> ListCaptionTracksAsync(
        string videoId, CancellationToken cancellationToken)
    {
        var payload = new
        {
            context = new
            {
                client = new
                {
                    clientName = "ANDROID",
                    clientVersion = "19.09.37",
                    androidSdkVersion = 30,
                    hl = "en",
                },
            },
            videoId,
        };

        JsonDocument doc;
        try
        {
            using var request = new HttpRequestMessage(HttpMethod.Post, PlayerUrl)
            {
                Content = JsonContent.Create(payload),
            };
            request.Headers.TryAddWithoutValidation(
                "User-Agent", "com.google.android.youtube/19.09.37 (Linux; U; Android 11)");
            using var response = await httpClient.SendAsync(request, cancellationToken);
            if (!response.IsSuccessStatusCode)
            {
                throw Unreachable(null);
            }
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            doc = await JsonDocument.ParseAsync(stream, cancellationToken: cancellationToken);
        }
        catch (ApiException)
        {
            throw;
        }
        catch (Exception ex)
        {
            throw Unreachable(ex);
        }

        using (doc)
        {
            var tracks = new List<CaptionTrack>();
            if (doc.RootElement.TryGetProperty("captions", out var captions)
                && captions.TryGetProperty("playerCaptionsTracklistRenderer", out var renderer)
                && renderer.TryGetProperty("captionTracks", out var arr)
                && arr.ValueKind == JsonValueKind.Array)
            {
                foreach (var t in arr.EnumerateArray())
                {
                    var baseUrl = t.TryGetProperty("baseUrl", out var b) ? b.GetString() : null;
                    if (string.IsNullOrEmpty(baseUrl))
                    {
                        continue;
                    }
                    var lang = t.TryGetProperty("languageCode", out var l) ? l.GetString() ?? string.Empty : string.Empty;
                    var kind = t.TryGetProperty("kind", out var k) ? k.GetString() : null;
                    tracks.Add(new CaptionTrack(baseUrl, lang, kind == "asr"));
                }
            }
            return tracks;
        }
    }

    private async Task<string> DownloadTranscriptAsync(
        string baseUrl, CancellationToken cancellationToken)
    {
        // SSRF defence-in-depth (D-578 security review): NEVER trust the host in the
        // baseUrl YouTube returned — re-validate it is an https YouTube/Google caption
        // host before fetching it. Combined with the no-redirect client (DI), a crafted
        // or MITM'd player response cannot steer this GET to an internal target. On
        // reject we throw the generic "unreachable" (reason only, the URL is never logged).
        if (!Uri.TryCreate(baseUrl, UriKind.Absolute, out var trackUri)
            || trackUri.Scheme != Uri.UriSchemeHttps
            || !IsCaptionHost(trackUri.Host))
        {
            throw Unreachable(null);
        }

        // Ask for the JSON3 caption format — clean to parse (events[].segs[].utf8).
        var url = baseUrl.Contains("fmt=", StringComparison.Ordinal)
            ? baseUrl
            : baseUrl + "&fmt=json3";

        JsonDocument doc;
        try
        {
            using var response = await httpClient.GetAsync(url, cancellationToken);
            if (!response.IsSuccessStatusCode)
            {
                throw Unreachable(null);
            }
            await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
            doc = await JsonDocument.ParseAsync(stream, cancellationToken: cancellationToken);
        }
        catch (ApiException)
        {
            throw;
        }
        catch (Exception ex)
        {
            throw Unreachable(ex);
        }

        using (doc)
        {
            var sb = new StringBuilder();
            if (doc.RootElement.TryGetProperty("events", out var events)
                && events.ValueKind == JsonValueKind.Array)
            {
                foreach (var ev in events.EnumerateArray())
                {
                    if (!ev.TryGetProperty("segs", out var segs)
                        || segs.ValueKind != JsonValueKind.Array)
                    {
                        continue;
                    }
                    var before = sb.Length;
                    foreach (var seg in segs.EnumerateArray())
                    {
                        // Word-timed pieces of one cue carry their own spacing — append raw.
                        if (seg.TryGetProperty("utf8", out var u))
                        {
                            sb.Append(u.GetString());
                        }
                    }
                    // Separate one caption cue/event from the next so adjacent lines
                    // don't run together when flattened below.
                    if (sb.Length > before)
                    {
                        sb.Append('\n');
                    }
                }
            }

            // Flatten the caption line breaks into readable running text.
            var pieces = sb.ToString()
                .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            return string.Join(" ", pieces).Trim();
        }
    }

    private static CaptionTrack ChooseTrack(
        IReadOnlyList<CaptionTrack> tracks, string? preferredLang)
    {
        if (!string.IsNullOrWhiteSpace(preferredLang))
        {
            var match = tracks.FirstOrDefault(t =>
                t.LanguageCode.StartsWith(preferredLang, StringComparison.OrdinalIgnoreCase));
            if (match is not null)
            {
                return match;
            }
        }
        // Prefer a human (non-ASR) track, else the first available.
        return tracks.FirstOrDefault(t => !t.AutoGenerated) ?? tracks[0];
    }

    // The hosts a legitimate YouTube caption baseUrl uses. Re-checked before the
    // second HTTP hop so a crafted/spoofed player response can't point the GET at an
    // internal host (SSRF defence-in-depth, D-578 review #1).
    private static bool IsCaptionHost(string host)
    {
        host = host.ToLowerInvariant();
        return host is "youtube.com" or "google.com" or "googlevideo.com"
            || host.EndsWith(".youtube.com", StringComparison.Ordinal)
            || host.EndsWith(".google.com", StringComparison.Ordinal)
            || host.EndsWith(".googlevideo.com", StringComparison.Ordinal);
    }

    private ApiException Unreachable(Exception? ex)
    {
        if (ex is not null)
        {
            logger.LogWarning(
                ex, "YouTube transcript fetch failed (the server may have no YouTube egress).");
        }
        return new ApiException(
            ErrorCodes.SubtitleFetchFailed, 502,
            "Could not fetch the subtitle from the video — the server may not be able to reach "
                + "YouTube. Paste or upload the subtitle instead.",
            "تعذّر جلب الترجمة من الفيديو — قد لا يستطيع الخادم الوصول إلى YouTube. "
                + "الصق النص أو ارفع ملف الترجمة بدلاً من ذلك.");
    }

    private sealed record CaptionTrack(string BaseUrl, string LanguageCode, bool AutoGenerated);
}
