import 'package:flutter/foundation.dart';
import 'package:simf_app/core/utils/saudi_time.dart';

/// One published session summary — mirrors
/// `SIMF.Contracts.*.PublicSessionSummary`
/// (`GET /app/programme/sessions/{id}/summary`, `AllowAnonymous`).
///
/// Every text field is bilingual (`*` EN + `*Arabic`). `keyPoints` /
/// `keyPointsArabic` are **newline-delimited** — one bullet per non-empty line,
/// split by [keyPointsLines]. `generatedByAi` drives the "generated by AI"
/// banner; `publishedAt` is the wire timestamp (kept as the raw string — the
/// screen only shows the date once parsed).
@immutable
class SessionSummary {
  const SessionSummary({
    required this.keyPoints,
    required this.keyPointsArabic,
    required this.recommendations,
    required this.recommendationsArabic,
    required this.speakers,
    required this.speakersArabic,
    required this.fullText,
    required this.fullTextArabic,
    required this.generatedByAi,
    this.publishedAtRaw,
    this.recordingUrl,
    this.summaryVideoUrl,
  });

  final String keyPoints;
  final String keyPointsArabic;
  final String recommendations;
  final String recommendationsArabic;
  final String speakers;
  final String speakersArabic;
  final String fullText;
  final String fullTextArabic;
  final bool generatedByAi;
  final String? publishedAtRaw;

  /// Item #35 — the session's FULL live recording feed (from the API's
  /// `recordingUrl`, sourced server-side from `Session.LiveStreamUrl`). Null =
  /// no recording feed → the summary screen hides the "full recording" player.
  final String? recordingUrl;

  /// Item #35 — the team's OPTIONAL short summary video (from the API's
  /// `summaryVideoUrl`). Null = no summary video → the screen hides that
  /// player.
  final String? summaryVideoUrl;

  String _picked(String ar, String en, bool isArabic) {
    final a = ar.trim();
    final e = en.trim();
    return isArabic ? (a.isNotEmpty ? a : e) : (e.isNotEmpty ? e : a);
  }

  /// The key-points block in the active language (may be empty).
  String localizedKeyPoints(bool isArabic) =>
      _picked(keyPointsArabic, keyPoints, isArabic);

  /// The recommendations block in the active language (may be empty).
  String localizedRecommendations(bool isArabic) =>
      _picked(recommendationsArabic, recommendations, isArabic);

  /// The speakers block in the active language (may be empty).
  String localizedSpeakers(bool isArabic) =>
      _picked(speakersArabic, speakers, isArabic);

  /// The full-text block in the active language (may be empty).
  String localizedFullText(bool isArabic) =>
      _picked(fullTextArabic, fullText, isArabic);

  /// The localized key points split into one bullet per non-empty line.
  List<String> keyPointsLines(bool isArabic) {
    return localizedKeyPoints(isArabic)
        .split('\n')
        .map((line) => line.trim())
        .where((line) => line.isNotEmpty)
        .toList(growable: false);
  }

  /// The published timestamp parsed off the wire, or null when missing /
  /// unparsable.
  DateTime? get publishedAt {
    final raw = publishedAtRaw;
    if (raw == null || raw.isEmpty) {
      return null;
    }
    return parseWireOrNull(raw);
  }

  static SessionSummary fromJson(Map<String, dynamic> json) => SessionSummary(
        keyPoints: json['keyPoints'] as String? ?? '',
        keyPointsArabic: json['keyPointsArabic'] as String? ?? '',
        recommendations: json['recommendations'] as String? ?? '',
        recommendationsArabic: json['recommendationsArabic'] as String? ?? '',
        speakers: json['speakers'] as String? ?? '',
        speakersArabic: json['speakersArabic'] as String? ?? '',
        fullText: json['fullText'] as String? ?? '',
        fullTextArabic: json['fullTextArabic'] as String? ?? '',
        generatedByAi: json['generatedByAi'] as bool? ?? false,
        publishedAtRaw: json['publishedAt'] as String?,
        recordingUrl: json['recordingUrl'] as String?,
        summaryVideoUrl: json['summaryVideoUrl'] as String?,
      );

  /// Decodes the `decodeData` payload (a JSON object) into a [SessionSummary].
  static SessionSummary fromData(Object? data) => SessionSummary.fromJson(
        (data as Map?)?.cast<String, dynamic>() ?? const <String, dynamic>{},
      );
}
