namespace SIMF.Contracts.Admin;

/// <summary>D-578 — request to fetch a session's subtitle transcript directly from
/// its video (YouTube). Stateless: the CP fills the caption textarea from the
/// response, the admin reviews it, then Saves the session normally.</summary>
/// <param name="VideoUrl">The YouTube video/live URL (usually the session's LiveStreamUrl).</param>
/// <param name="Lang">Optional 2-letter language hint ("ar"/"en"); null = best available.</param>
public sealed record FetchSubtitleRequest(string VideoUrl, string? Lang = null);

/// <summary>D-578 — the fetched transcript, for the CP to drop into a caption field.</summary>
public sealed record FetchSubtitleResponse(string Text, string LanguageCode, bool AutoGenerated);
