s/\bKsaPage\b/SimfPageShell/g
s/\bKsaBackButton\b/SimfCircledBackButton/g
s/\bKsaMenuButton\b/SimfMenuButton/g
s/\bKsaRefresh\b/SimfPullToRefresh/g
s/\bKsaPullable\b/SimfPullableHost/g
s/\bKsaLangThemeButtons\b/SimfLangThemeButtons/g
s/\bKsaHeaderActions\b/SimfHeaderActions/g
s/\bKsaSweep\b/SimfSweepBackground/g
s/\bKsaCard\b/SimfCard/g
s/\bKsaSectionHeader\b/SimfSectionHeader/g
s/\bKsaLinkRow\b/SimfLinkRow/g
s/\bKsaTileRow\b/SimfTileRow/g
s/\bKsaNavTile\b/SimfNavTile/g
s/\bKsaStatTile\b/SimfStatTile/g
s/\bKsaAvatar\b/SimfAvatar/g
s/\bKsaListRow\b/SimfListRow/g
s/\bKsaErrorState\b/SimfErrorState/g
s/\bKsaEmptyState\b/SimfEmptyState/g
s/\bKsaSearchField\b/SimfSearchField/g
s/\bKsaAuthScaffold\b/AuthPageShell/g
s/\bKsaSubmitButton\b/AuthSubmitButton/g
s/\bKsaFieldLabel\b/FormFieldLabel/g
s/\bksaBackOrHome\b/backOrHome/g
s/\bksaInputTextStyle\b/authInputTextStyle/g
s/\bksaInputDecoration\b/authInputDecoration/g
s/\bksaGoldButtonStyle\b/authSubmitButtonStyle/g
s/ksa_shell\.dart/simf_page_shell.dart/g
s/ksa_search_field\.dart/simf_search_field.dart/g
