// D-820 — the Dart badge decoder must agree byte for byte with the C# encoder
// (SIMF.Common.Badges.EventBadgeCodec). The fixtures below were produced by
// that encoder; if this file goes red after a codec change, the shipped app
// stopped being able to read badges the desks are printing.
import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:simf_app/features/gates/data/offline_badge.dart';

void main() {
  // The test key from SIMF.Api.Tests/OfflineBadgeUploadTests: bytes 0..31.
  final key = Uint8List.fromList(List<int>.generate(32, (i) => i));

  group('OfflineBadge', () {
    test('reads the key version without decrypting', () {
      expect(OfflineBadge.readKeyVersion('1ABCDEF'), 1);
      expect(OfflineBadge.readKeyVersion('0ABCDEF'), 0);
      // Crockford folds the look-alikes, which is what lets a damaged badge be
      // typed in by hand at the desk.
      expect(OfflineBadge.readKeyVersion('IABCDEF'), 1);
      expect(OfflineBadge.readKeyVersion('OABCDEF'), 0);
      expect(OfflineBadge.readKeyVersion(''), isNull);
      expect(OfflineBadge.readKeyVersion('U'), isNull);
    });

    test('rejects a payload longer than the accepted maximum', () {
      final huge = 'A' * (OfflineBadge.maxEncodedLength + 1);
      expect(OfflineBadge.decode(huge, key), isNull);
      expect(OfflineBadge.readKeyVersion(huge), isNull);
    });

    test('rejects a key that is not AES-256', () {
      expect(OfflineBadge.decode('1ABCDEF', Uint8List(16)), isNull);
    });

    test('rejects a badge whose authentication tag does not verify', () {
      // A well-formed base32 body under a key that never produced it.
      const forged = '1ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ';
      expect(OfflineBadge.decode(forged, key), isNull);
    });

    test('rejects malformed input without throwing', () {
      for (final bad in <String>['', '1', '1!!!!', '1U', '1ABC']) {
        expect(OfflineBadge.decode(bad, key), isNull, reason: bad);
      }
    });

    test('maps a sequence to the QR id the server stores', () {
      expect(
        const OfflineBadge(profileTypeCode: 1, sequence: 3000042).qrId,
        'W00003000042',
      );
      expect(
        const OfflineBadge(profileTypeCode: 1, sequence: 1).qrId,
        'W00000000001',
      );
      // Out of range: no id rather than a wrong one.
      expect(const OfflineBadge(profileTypeCode: 1, sequence: 0).qrId, '');
    });
  });

  group('cross-language contract with the C# encoder', () {
    // Every string below was PRODUCED by EventBadgeCodec.Encode under the key
    // above. The same five fixtures are pinned in
    // SIMF.Application.Tests/EventBadgeCodecTests, so if the two languages ever
    // drift, both suites go red instead of the app silently failing to read
    // badges the desks are already printing.
    //
    // The nonce is random, so these cannot be regenerated by re-encoding and
    // compared — they are decode fixtures. Do not hand-edit them.
    const fixtures = <String, List<int>>{
      // encoded: [profileTypeCode, sequence]
      '1514B39C8841QMMTQCSS7A85NJ8T678WZYZR4E4SE4XRC67CY1GH81VCDWAAG': [
        1,
        3000042,
      ],
      '1KQ6Z2HH37PJBNQ202Z54CS9V5TWARA380RB0RJ73M5R6XMS1K8': [
        2,
        1,
      ],
      '1P04044WDQG6Z6APZ3B15AJZ8SW7MRQEJ3EZGX2Z5H4ZSPYFCSYYPYE0598MG': [
        7,
        4999999,
      ],
      '1ZMYK8EM39BX9SSHK6KEHYNH6EAVK0M914SAY5A8G364DM3K307XK9CEE6A029D7QB0': [
        30,
        9999999999,
      ],
    };

    test('decodes every badge the C# encoder produced', () {
      fixtures.forEach((encoded, expected) {
        final badge = OfflineBadge.decode(encoded, key);
        expect(badge, isNotNull, reason: encoded);
        expect(badge!.profileTypeCode, expected[0], reason: encoded);
        expect(badge.sequence, expected[1], reason: encoded);
      });
    });

    test('survives the uppercasing every scan path applies', () {
      // QrId.Normalise upper-cases on the server, and an operator may type a
      // damaged code in lower case. Base32 was chosen over base64 precisely so
      // this cannot corrupt the payload.
      const encoded = '1514B39C8841QMMTQCSS7A85NJ8T678WZYZR4E4SE4XRC67CY1GH81VCDWAAG';
      final badge = OfflineBadge.decode(encoded.toLowerCase(), key);
      expect(badge?.sequence, 3000042);
    });

    test('reads a badge stamped with the previous key version', () {
      const encoded = '0DDZYS5R9HVKXNQP7KQHR7FDRMPNAZ1ZG2E976DKNF5GGR57Y1AHB3F73NF2G';
      expect(OfflineBadge.readKeyVersion(encoded), 0);
      expect(OfflineBadge.decode(encoded, key)?.sequence, 3000043);
    });

    test('a real badge stays inside the QR-id audit column', () {
      // GateScans.QrIdAtScan is nvarchar(96) after the D-820 widening, and the
      // server stores the whole blob so it can decrypt independently. A typical
      // badge is 61 characters; the 10-digit-sequence extreme is 67.
      for (final encoded in fixtures.keys) {
        expect(encoded.length, lessThanOrEqualTo(96), reason: encoded);
      }
    });

    test('the fixture key is the one the C# tests use', () {
      expect(base64Encode(key), 'AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=');
    });
  });
}
