// D-820 — the Dart badge decoder must agree byte for byte with the C# encoder
// (SIMF.Common.Badges.EventBadgeCodec). The fixtures below were produced by
// that encoder; if this file goes red after a codec change, the shipped app
// stopped being able to read badges the desks are printing.
//
// ignore_for_file: lines_longer_than_80_chars
//
// Each fixture is one base32 token produced by the other language. Wrapping one
// across lines would make it unreadable exactly where it has to be compared
// character for character against the C# side, so the rule is suppressed here
// with a reason rather than obeyed — the same call this branch already made for
// its other suppressions.
import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:simf_app/features/gates/data/offline_badge.dart';

void main() {
  // The test key from SIMF.Api.Tests/OfflineBadgeUploadTests: bytes 0..31.
  final key = Uint8List.fromList(List<int>.generate(32, (i) => i));

  group('OfflineBadge', () {
    test('reads the key version without decrypting', () {
      expect(OfflineBadge.readKeyVersion('1ABCDEF'), 1);
      expect(OfflineBadge.readKeyVersion('0ABCDEF'), 0);
      // Crockford folds the look-alikes, which is what lets a damaged badge be
      // typed in by hand at the desk.
      expect(OfflineBadge.readKeyVersion('IABCDEF'), 1);
      expect(OfflineBadge.readKeyVersion('OABCDEF'), 0);
      expect(OfflineBadge.readKeyVersion(''), isNull);
      expect(OfflineBadge.readKeyVersion('U'), isNull);
    });

    test('rejects a payload longer than the accepted maximum', () {
      final huge = 'A' * (OfflineBadge.maxEncodedLength + 1);
      expect(OfflineBadge.decode(huge, key), isNull);
      expect(OfflineBadge.readKeyVersion(huge), isNull);
    });

    test('rejects a key that is not AES-256', () {
      expect(OfflineBadge.decode('1ABCDEF', Uint8List(16)), isNull);
    });

    test('rejects a badge whose authentication tag does not verify', () {
      // A well-formed base32 body under a key that never produced it.
      const forged = '1ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ';
      expect(OfflineBadge.decode(forged, key), isNull);
    });

    test('rejects malformed input without throwing', () {
      for (final bad in <String>['', '1', '1!!!!', '1U', '1ABC']) {
        expect(OfflineBadge.decode(bad, key), isNull, reason: bad);
      }
    });

  });

  group('cross-language contract with the C# encoder', () {
    // Every string below was PRODUCED by EventBadgeCodec.Encode under the key
    // above. The same five fixtures are pinned in
    // SIMF.Application.Tests/EventBadgeCodecTests, so if the two languages ever
    // drift, both suites go red instead of the app silently failing to read
    // badges the desks are already printing.
    //
    // The nonce is random, so these cannot be regenerated by re-encoding and
    // compared — they are decode fixtures. Do not hand-edit them.
    // encoded: [profileId, editionYear, profileTypeCode]
    const fixtures = <String, List<Object>>{
      '15F9NADHE9H94MTGBNK7WMMWB6Q3GTDED9NMBF161ZHXRFWS8KFRCYG8SWRCQ0NP1EJQ0SQXAS0NRA':
          ['11111111-2222-3333-4444-555555555555', 2026, 1],
      '11Z0KE14GCKKEHCT1MYEYJ6QK1Q4S6WCG5694NS23BMPNBWXYB85TDTN3C3XKQA7JD92EFHFNMQN20':
          ['00000000-0000-0000-0000-000000000001', 2026, 2],
      '1CVTC4V9WG32MWFARN461D6MK7EZ7A0B7SW1S7QZW4EJCXYSYSFBCZ3M69YD16B3TP591QT4GPXPRG':
          ['aabbccdd-eeff-0011-2233-445566778899', 2027, 7],
      'Y62XPW76MG7BZRV8SKQRWBDFNJFV6QS1JXAYRGEA12GHP54CVBKWKS32QXD0VP5YM9MH7WHE9R71S8':
          ['ffffffff-ffff-ffff-ffff-ffffffffffff', 2999, 65535],
      '00Y8GQ011PGAFNGMDY97JQSEVMD552KA0DZNFJ66RVPZ261AZ3NPYQFJPC3EC1KWNV0ETN7K5AQ9Y6':
          ['12345678-9abc-def0-1234-56789abcdef0', 2000, 0],
    };

    test('decodes every badge the C# encoder produced', () {
      fixtures.forEach((encoded, expected) {
        final badge = OfflineBadge.decode(encoded, key);
        expect(badge, isNotNull, reason: encoded);
        // The profile id first: it is what the server seeks by primary key, so
        // a byte-order slip between the two languages would resolve every badge
        // to nobody while still decrypting cleanly.
        expect(badge!.profileId, expected[0], reason: encoded);
        expect(badge.editionYear, expected[1], reason: encoded);
        expect(badge.profileTypeCode, expected[2], reason: encoded);
      });
    });

    test('survives the uppercasing every scan path applies', () {
      // QrId.Normalise upper-cases on the server, and an operator may type a
      // damaged code in lower case. Base32 was chosen over base64 precisely so
      // this cannot corrupt the payload.
      const encoded =
          '15F9NADHE9H94MTGBNK7WMMWB6Q3GTDED9NMBF161ZHXRFWS8KFRCYG8SWRCQ0NP1EJQ0SQXAS0NRA';
      final badge = OfflineBadge.decode(encoded.toLowerCase(), key);
      expect(badge?.profileId, '11111111-2222-3333-4444-555555555555');
    });

    test('reads a badge stamped with the previous key version', () {
      const encoded =
          '00Y8GQ011PGAFNGMDY97JQSEVMD552KA0DZNFJ66RVPZ261AZ3NPYQFJPC3EC1KWNV0ETN7K5AQ9Y6';
      expect(OfflineBadge.readKeyVersion(encoded), 0);
      expect(
        OfflineBadge.decode(encoded, key)?.profileId,
        '12345678-9abc-def0-1234-56789abcdef0',
      );
    });

    test('a real badge stays inside the QR-id audit column', () {
      // GateScans.QrIdAtScan is nvarchar(96), and the server stores the whole
      // blob so it can decrypt independently. Every badge is exactly 78
      // characters now: the payload is fixed-width, so there is no longer a
      // typical case and an extreme one.
      for (final encoded in fixtures.keys) {
        expect(encoded.length, 78, reason: encoded);
        expect(encoded.length, lessThanOrEqualTo(96), reason: encoded);
      }
    });

    test('the fixture key is the one the C# tests use', () {
      expect(base64Encode(key), 'AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=');
    });
  });
}
