# =============================================================================
# SIMF - SimfAPI production environment variables (TEMPLATE - empty values)
#
# Per SIMF-OPS-001 section 6: production overrides and every secret are applied
# as MACHINE-scope environment variables on the server by this per-service
# script. The committed copy is a TEMPLATE with empty values - NEVER commit real
# secret values. Fill the values on the server, run as Administrator, then
# restart the IIS app pool so w3wp picks them up.
#
# Naming: SIMF_ + ASP.NET Core double-underscore convention (SIMF_Section__Key).
# The apps register AddEnvironmentVariables("SIMF_"), which strips the prefix, so
# SIMF_ConnectionStrings__SimfAppDb binds to ConnectionStrings:SimfAppDb.
# EXCEPTION: ASPNETCORE_ENVIRONMENT is read by the host before configuration
# sources load, so it stays UN-prefixed.
#
# Array values bind by index: SIMF_ReverseProxy__KnownProxies__0, __1, __2, ...
#
# Secret generation (SIMF-OPS-001 section B.3):
#   SIMF_Jwt__SigningKey                      : openssl rand -base64 48
#   SIMF_Storage__UserIdDocumentEncryptionKey : openssl rand -base64 32
#   SIMF_Ai__PromptHash__Secret               : auto-generated by this script (generate-if-absent)
# =============================================================================

#Requires -RunAsAdministrator

$ErrorActionPreference = "Stop"

# name -> value. An empty value is SKIPPED (warned), so running the unedited
# template never clobbers a required secret with an empty string.
$vars = [ordered]@{
    "ASPNETCORE_ENVIRONMENT"                       = "Production"  # [REQUIRED] host-level - NOT prefixed

    # --- Databases (SIMF-OPS-001 B.1) ---
    "SIMF_ConnectionStrings__SimfIdentityDb"       = ""  # [REQUIRED][SECRET] Identity DB
    "SIMF_ConnectionStrings__SimfAppDb"            = ""  # [REQUIRED][SECRET] App DB

    # --- JWT ---
    "SIMF_Jwt__SigningKey"                         = ""  # [REQUIRED][SECRET] openssl rand -base64 48
    # SIMF_Jwt__Issuer / __Audience / __StreamAudience / __StreamTokenMinutes and
    # the two token-lifetime caps below all have appsettings defaults - override
    # only if needed. The lifetimes are the D-443 NCA caps; do NOT raise them
    # past the review limits (access <= 5 min, session <= 1 day):
    #   SIMF_Jwt__AccessTokenMinutes   default 5   (NCA cap: not more than 5 minutes)
    #   SIMF_Jwt__SessionLifetimeHours default 24  (NCA cap: not more than 1 day)

    # --- Email / SMTP ---
    "SIMF_Email__Host"                             = ""  # [REQUIRED]
    "SIMF_Email__Port"                             = ""  # optional (default 587)
    "SIMF_Email__User"                             = ""  # [REQUIRED]
    "SIMF_Email__Password"                         = ""  # [REQUIRED][SECRET]
    "SIMF_Email__FromAddress"                      = ""  # optional (default no-reply@simf.example)
    "SIMF_Email__FromName"                         = ""  # optional (default SIMF)

    # --- Bootstrap super-admin (rotate post first login - SIMF-OPS-001 B.6) ---
    "SIMF_SuperAdmin__Email"                       = ""  # [REQUIRED]
    "SIMF_SuperAdmin__TempPassword"                = ""  # [REQUIRED][SECRET]
    "SIMF_SuperAdmin__TotpSecret"                  = ""  # [REQUIRED][SECRET]

    # --- Filesystem storage ---
    "SIMF_Storage__AvatarBase"                     = ""  # [REQUIRED] validated at startup
    "SIMF_Storage__UserIdDocumentBase"             = ""  # [REQUIRED] encrypted ID-image store
    "SIMF_Storage__UserIdDocumentEncryptionKey"    = ""  # [REQUIRED][SECRET] openssl rand -base64 32
    "SIMF_Storage__LogDirectory"                   = ""  # optional (default logs)

    # --- AI provider (D-484: this deployment uses Anthropic/Claude) ---
    # DefaultProvider redirects every Echo-default prompt to a real backend
    # without editing each prompt; "Anthropic" is the chosen provider (non-secret).
    "SIMF_Ai__DefaultProvider"                     = "Anthropic"  # Echo | OpenAi | AzureOpenAi | Anthropic
    # Claude (Anthropic Messages API). BaseUrl + AnthropicVersion have code
    # defaults (https://api.anthropic.com / 2023-06-01); only the key is required.
    "SIMF_Ai__Anthropic__ApiKey"                   = ""  # [REQUIRED for Anthropic][SECRET] sk-ant-…  (set on server / set-env-api.local.ps1)
    "SIMF_Ai__Anthropic__DefaultModel"             = "claude-haiku-4-5-20251001"  # non-secret model id
    "SIMF_Ai__Anthropic__BaseUrl"                  = ""  # optional (default https://api.anthropic.com)
    "SIMF_Ai__Anthropic__AnthropicVersion"         = ""  # optional (default 2023-06-01)
    # OpenAI kept available (only used by a prompt explicitly pinned to OpenAi).
    "SIMF_Ai__OpenAi__ApiKey"                      = ""  # [SECRET] required only if a prompt uses OpenAi
    "SIMF_Ai__OpenAi__BaseUrl"                     = ""  # optional (default https://api.openai.com/v1)
    "SIMF_Ai__OpenAi__DefaultModel"                = ""  # optional (default gpt-4o-mini)
    # SIMF_Ai__PromptHash__Secret is auto-generated below (generate-if-absent) - never hand-filled.

    # --- Reverse proxy (trusted hops for X-Forwarded-For) ---
    "SIMF_ReverseProxy__KnownProxies__0"           = ""  # [REQUIRED for prod] first trusted proxy IP; add __1, __2 ...

    # --- OpenAPI / Swagger UI (D-355) — OFF in prod by default. If you set
    #     SIMF_Swagger__AllowSwagger=true in Production, BOTH Basic-auth creds
    #     below become REQUIRED or the app REFUSES TO START (HTTP 500.30). ---
    "SIMF_Swagger__Username"                       = ""  # [REQUIRED only if AllowSwagger=true][SECRET]
    "SIMF_Swagger__Password"                       = ""  # [REQUIRED only if AllowSwagger=true][SECRET]

    # --- Web-app CORS (D-376) — ONLY when the published Flutter web app is
    #     hosted on a DIFFERENT origin than this API; empty = no CORS.
    #     The origin is public (not a secret), so the real production value is
    #     committed here: the app-web IIS site at simf_app.zagali-ict.com.
    #     Origin only — scheme + host, NO trailing slash, NO path. ---
    "SIMF_Cors__WebAppOrigins__0"                  = "https://simf_app.zagali-ict.com"  # add __1 ... for more origins

    # --- Rate limits (defaults exist; tighten for a public-facing deploy) ---
    "SIMF_RateLimit__PermitLimit"                  = ""  # optional (default 20)
    "SIMF_RateLimit__WindowSeconds"                = ""  # optional (default 60)

    # --- Media / presentation / recording storage roots ---
    "SIMF_MediaImageStorage__RootPath"             = ""  # optional (default App_Data/media)
    "SIMF_SpeakerPresentationStorage__RootPath"    = ""  # optional (default App_Data/presentations)
    "SIMF_SessionRecordingStorage__RootPath"       = ""  # optional (default App_Data/recordings)
    "SIMF_SessionRecordingStorage__MaxUploadBytes" = ""  # optional (default 1073741824)
}

$set = 0
$skipped = 0
foreach ($name in $vars.Keys) {
    $value = $vars[$name]
    if ([string]::IsNullOrWhiteSpace($value)) {
        Write-Warning "SKIP (empty): $name  - fill this in before a real deploy"
        $skipped++
        continue
    }
    [Environment]::SetEnvironmentVariable($name, $value, [EnvironmentVariableTarget]::Machine)
    Write-Host "set: $name"
    $set++
}

Write-Host ""
Write-Host "SimfAPI env: $set set, $skipped skipped (empty)."

# --- Auto-generate the prompt-hash secret if it was never set ---------------------
# SIMF_Ai__PromptHash__Secret is boot-critical (Production guard M4) but it is an
# INTERNAL value (not an external credential), so generate a stable 32-byte secret
# here on first run instead of hand-filling it - one run of this script is enough.
# Never regenerated once present (rotating it would invalidate every existing stored
# prompt hash). Multi-node prod: generate once and copy the SAME value to each node.
$promptHashName = "SIMF_Ai__PromptHash__Secret"
$existingHash = [Environment]::GetEnvironmentVariable($promptHashName, [EnvironmentVariableTarget]::Machine)
if ([string]::IsNullOrWhiteSpace($existingHash)) {
    $bytes = New-Object byte[] 32
    ([System.Security.Cryptography.RandomNumberGenerator]::Create()).GetBytes($bytes)
    [Environment]::SetEnvironmentVariable($promptHashName, [Convert]::ToBase64String($bytes), [EnvironmentVariableTarget]::Machine)
    Write-Host "set:  $promptHashName  (freshly generated, 32-byte base64 - now stable)"
}
else {
    Write-Host "keep: $promptHashName  (already set - left unchanged)"
}

# --- Boot-critical completeness gate (added after the 2026-06-22 deploy outage) ---
# Every variable below HARD-FAILS the API at startup in Production (the Program.cs
# guards + the Ensure*Configured calls + the StorageOptions ValidateOnStart hook).
# If any is empty in the Machine environment, the next app-pool recycle boot-fails
# with "HTTP Error 500.30 - ASP.NET Core app failed to start". This gate reads the
# resulting Machine values (not just this script's table) so a variable that was
# never carried over from an older provisioning is caught here, not in prod.
$bootCritical = @(
    "SIMF_ConnectionStrings__SimfIdentityDb"
    "SIMF_ConnectionStrings__SimfAppDb"
    "SIMF_Jwt__SigningKey"
    "SIMF_SuperAdmin__TempPassword"
    "SIMF_ReverseProxy__KnownProxies__0"
    "SIMF_Ai__PromptHash__Secret"                 # Production guard (M4)
    "SIMF_Storage__UserIdDocumentEncryptionKey"   # Production guard (A2-10)
    "SIMF_Storage__AvatarBase"                    # ValidateOnStart (D-074)
    "SIMF_Storage__UserIdDocumentBase"
)
$missing = @()
foreach ($name in $bootCritical) {
    $live = [Environment]::GetEnvironmentVariable($name, [EnvironmentVariableTarget]::Machine)
    if ([string]::IsNullOrWhiteSpace($live)) { $missing += $name }
}
# If Swagger UI is turned on in prod, its Basic-auth creds become boot-critical too.
$swaggerOn = [Environment]::GetEnvironmentVariable("SIMF_Swagger__AllowSwagger", [EnvironmentVariableTarget]::Machine)
if ($swaggerOn -eq "true") {
    foreach ($name in @("SIMF_Swagger__Username", "SIMF_Swagger__Password")) {
        $live = [Environment]::GetEnvironmentVariable($name, [EnvironmentVariableTarget]::Machine)
        if ([string]::IsNullOrWhiteSpace($live)) { $missing += $name }
    }
}

Write-Host ""
if ($missing.Count -gt 0) {
    Write-Warning "BOOT-CRITICAL variables still EMPTY - the API will NOT start in Production:"
    $missing | ForEach-Object { Write-Host "  MISSING: $_" -ForegroundColor Red }
    Write-Host "Set these (Machine scope) and re-run this script BEFORE recycling the app pool." -ForegroundColor Red
} else {
    Write-Host "All boot-critical variables are present." -ForegroundColor Green
    Write-Host "Restart the IIS app pool (or the server) so w3wp picks up the new Machine-scope variables."
}
