<#
.SYNOPSIS
Stands up the isolated environment the operations manual is captured from.

.DESCRIPTION
Runs SIMF.Api and SIMF.ControlPanel against a DEDICATED pair of databases
(SIMF_Identity_Doc / SIMF_App_Doc) so the working SIMF_Identity / SIMF_App are
never touched, and sets every configuration key those flows need as a
PROCESS-scoped variable so the machine's real production values stay untouched.

Why each key is here, rather than only the ones that fail at boot:

  Jwt:SigningKey                        Program.cs refuses a key under 32 bytes;
                                        without it every sign-in returns 500.
  Storage:UserIdDocumentEncryptionKey   The AES-GCM PII key. OUTSIDE Production
                                        this does not fail at boot - it throws at
                                        RUNTIME on every write of a national ID,
                                        Iqama, passport or mobile number, i.e. in
                                        the middle of the visitor-create capture.
  FileStorage:EncryptionKey             Same shape for the file store: it
                                        fail-fasts on the first upload, i.e. the
                                        profile-photo capture.

The secrets are generated once into .tmp/manual-env/secrets.local.ps1 (the whole
.tmp tree is gitignored) and reused, so a re-run does not invalidate the TOTP
secret that was already paired.

.PARAMETER Reset
Drop and recreate both documentation databases before starting. The API
re-creates and re-seeds them on boot.

.PARAMETER Stop
Stop the documentation API and Control Panel and exit.
#>
[CmdletBinding()]
param(
    [switch]$Reset,
    [switch]$Stop
)

$ErrorActionPreference = 'Stop'

$repo     = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$envDir   = Join-Path $repo '.tmp\manual-env'
$secrets  = Join-Path $envDir 'secrets.local.ps1'
$filesDir = Join-Path $envDir 'files'
$logDir   = Join-Path $envDir 'logs'

$SqlServer   = 'localhost'
$IdentityDb  = 'SIMF_Identity_Doc'
$AppDb       = 'SIMF_App_Doc'
$ApiUrl      = 'http://localhost:5175'
$CpUrl       = 'http://localhost:5158'

function Stop-DocStack {
    $stopped = 0
    foreach ($port in @(5175, 5158)) {
        $conns = Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue
        foreach ($c in $conns) {
            try {
                Stop-Process -Id $c.OwningProcess -Force -ErrorAction Stop
                $stopped++
            } catch { }
        }
    }
    Write-Output "Stopped $stopped listener process(es) on 5175/5158."
}

if ($Stop) { Stop-DocStack; return }

New-Item -ItemType Directory -Force -Path $envDir, $filesDir, $logDir | Out-Null

# ---------------------------------------------------------------- secrets ----
if (-not (Test-Path $secrets)) {

    # RandomNumberGenerator.Fill is .NET Core only; Windows PowerShell 5.1 runs
    # on .NET Framework, where RNGCryptoServiceProvider.GetBytes is the equivalent.
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider

    function New-Base64Key {
        param($Rng)
        $bytes = New-Object byte[] 32
        $Rng.GetBytes($bytes)
        [Convert]::ToBase64String($bytes)
    }

    # RFC 4648 base32, which is the alphabet an authenticator app expects.
    function New-Base32Secret {
        param($Rng)
        $alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'
        $bytes = New-Object byte[] 20
        $Rng.GetBytes($bytes)
        $chars = foreach ($b in $bytes) { $alphabet[$b % 32] }
        -join $chars
    }

    # Must satisfy SimfPasswordValidator: 8-128 chars, upper + lower + digit +
    # special, no 3 identical in a row, and NO 3-character ascending or
    # descending run inside one class. A password containing 12345 is rejected,
    # and the seeder then logs the reason and boots healthy, so every sign-in
    # fails afterwards with nothing visibly wrong.
    $docPassword = 'Kx7#mQ4v!Zt2'

    $lines = @(
        '# Generated by tools/manual/doc-env.ps1 - throwaway values for the',
        '# documentation capture environment ONLY. Never reuse these anywhere',
        '# else. This file lives under .tmp/, which is gitignored.',
        ('$DocJwtKey     = ''{0}''' -f (New-Base64Key $rng)),
        ('$DocPiiKey     = ''{0}''' -f (New-Base64Key $rng)),
        ('$DocFileKek    = ''{0}''' -f (New-Base64Key $rng)),
        ('$DocPromptHmac = ''{0}''' -f (New-Base64Key $rng)),
        ('$DocTotpSecret = ''{0}''' -f (New-Base32Secret $rng)),
        ('$DocPassword   = ''{0}''' -f $docPassword)
    )
    Set-Content -Path $secrets -Value $lines -Encoding utf8

    Write-Output "Generated throwaway documentation secrets -> $secrets"
}

. $secrets

# ------------------------------------------------------------- databases ----
if ($Reset) {
    Write-Output "Dropping and recreating $IdentityDb / $AppDb ..."
    foreach ($db in @($IdentityDb, $AppDb)) {
        $sql = "IF DB_ID('$db') IS NOT NULL BEGIN ALTER DATABASE [$db] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [$db]; END"
        sqlcmd -S $SqlServer -E -Q $sql | Out-Null
    }
}
foreach ($db in @($IdentityDb, $AppDb)) {
    sqlcmd -S $SqlServer -E -Q "IF DB_ID('$db') IS NULL CREATE DATABASE [$db];" | Out-Null
}
Write-Output "Databases ready: $IdentityDb, $AppDb"

# ----------------------------------------------------------- environment ----
$connectionTemplate = 'Server={0};Database={1};Trusted_Connection=True;TrustServerCertificate=True;Encrypt=True;Connect Timeout=15;Application Name=SIMF.Manual'

$env:ASPNETCORE_ENVIRONMENT = 'Development'

$env:SIMF_API_ConnectionStrings__SimfIdentityDb    = ($connectionTemplate -f $SqlServer, $IdentityDb)
$env:SIMF_API_ConnectionStrings__SimfAppDb         = ($connectionTemplate -f $SqlServer, $AppDb)
$env:SIMF_API_Jwt__SigningKey                      = $DocJwtKey
$env:SIMF_API_Storage__UserIdDocumentEncryptionKey = $DocPiiKey
$env:SIMF_API_Storage__LogDirectory                = $logDir
$env:SIMF_API_FileStorage__EncryptionKey           = $DocFileKek
$env:SIMF_API_FileStorage__RootPath                = $filesDir
$env:SIMF_API_Ai__PromptHash__Secret               = $DocPromptHmac
$env:SIMF_API_SuperAdmin__Email                    = 'superadmin@simrsnf.com'
$env:SIMF_API_SuperAdmin__TempPassword             = $DocPassword
$env:SIMF_API_SuperAdmin__TotpSecret               = $DocTotpSecret
$env:SIMF_API_SuperAdmin__PasswordChangeRequired   = 'true'
$env:SIMF_API_Seed__DemoPassword                   = $DocPassword
$env:SIMF_API_Seed__EnableDemoAccounts             = 'true'

# The capture walks ~112 pages in three minutes. Every Control Panel page load
# fetches /account/api/profile for the header, so a sweep at that pace exhausts
# the per-IP bucket (PermitLimit defaults to 20 per 60s) and the header request
# starts answering 429. It does not damage the page - grids render from their
# own endpoints - but it fills the capture report with console errors and
# destroys the "zero console errors" signal the manual's verification gate
# depends on. Raised HERE ONLY, in the documentation environment; the manual
# documents the real shipped defaults, which are unchanged.
$env:SIMF_API_RateLimit__PermitLimit        = '100000'
$env:SIMF_API_RateLimit__LookupPermitLimit  = '100000'
$env:SIMF_API_RateLimit__GlobalPermitLimit  = '100000'
$env:SIMF_API_RateLimit__EmailPermitLimit   = '100000'

$env:SIMF_CP_Api__BaseUrl          = "$ApiUrl/"
$env:SIMF_CP_Storage__LogDirectory = $logDir

# ---------------------------------------------------------------- launch ----
Stop-DocStack

$apiDir = Join-Path $repo 'src\Backend\SIMF.Api'
$cpDir  = Join-Path $repo 'src\ControlPanel\SIMF.ControlPanel'

Start-Process dotnet `
    -ArgumentList 'run', '-c', 'Release', '--no-build', '--no-launch-profile', '--urls', $ApiUrl `
    -WorkingDirectory $apiDir -WindowStyle Hidden `
    -RedirectStandardOutput (Join-Path $logDir 'api.out.log') `
    -RedirectStandardError  (Join-Path $logDir 'api.err.log')

Write-Output "API starting on $ApiUrl (migrations + seed run on first boot; this takes a while)."

$deadline = (Get-Date).AddMinutes(8)
$healthy = $false
while ((Get-Date) -lt $deadline) {
    try {
        $r = Invoke-WebRequest -Uri "$ApiUrl/health" -UseBasicParsing -TimeoutSec 5
        if ($r.StatusCode -eq 200) { $healthy = $true; break }
    } catch { Start-Sleep -Seconds 3 }
}
if (-not $healthy) {
    Write-Output "API did not become healthy. Tail of api.err.log:"
    Get-Content (Join-Path $logDir 'api.err.log') -Tail 40 -ErrorAction SilentlyContinue
    throw "API health check failed."
}
Write-Output "API healthy."

Start-Process dotnet `
    -ArgumentList 'run', '-c', 'Release', '--no-build', '--no-launch-profile', '--urls', $CpUrl `
    -WorkingDirectory $cpDir -WindowStyle Hidden `
    -RedirectStandardOutput (Join-Path $logDir 'cp.out.log') `
    -RedirectStandardError  (Join-Path $logDir 'cp.err.log')

$deadline = (Get-Date).AddMinutes(4)
$cpUp = $false
while ((Get-Date) -lt $deadline) {
    try {
        $r = Invoke-WebRequest -Uri "$CpUrl/login" -UseBasicParsing -TimeoutSec 5
        if ($r.StatusCode -eq 200) { $cpUp = $true; break }
    } catch { Start-Sleep -Seconds 3 }
}
if (-not $cpUp) {
    Write-Output "Control Panel did not answer. Tail of cp.err.log:"
    Get-Content (Join-Path $logDir 'cp.err.log') -Tail 40 -ErrorAction SilentlyContinue
    throw "Control Panel start failed."
}

Write-Output ""
Write-Output "Documentation stack is up:"
Write-Output "  API           $ApiUrl  (health: $ApiUrl/health)"
Write-Output "  Control Panel $CpUrl   (sign in: $CpUrl/login)"
Write-Output "  Databases     $IdentityDb / $AppDb"
Write-Output "  File store    $filesDir"
Write-Output "  Secrets       $secrets"
