// Tests: D-959 - incremental migrations, replacing D-925's regenerate-in-place.
//
// The rule this file used to enforce was: exactly ONE migration per context, at a
// pinned id, regenerated by tools/migrations/Regenerate-Migration.ps1 on every
// schema change. It solved a real merge hazard (below) and created a worse one.
//
// A REGENERATED MIGRATION NEVER REACHES A DATABASE THAT ALREADY HAS ONE.
// __EFMigrationsHistory records 00000000000000_InitialCreate as applied, so
// MigrateAsync finds nothing pending and applies nothing. Every schema change
// between 2026-08-14 and 2026-09-07 therefore reached a live database only if
// somebody remembered to hand-write a matching docs/migrations/2026/*_Hotfix.sql.
// Several were not written. The local development pair was found missing
// ProfileIdentityDocuments, BadgeBatchItems and UserProfile.OrganisationOther
// while EF believed the schema was current - and the production pair carries the
// same pinned history row.
//
// The owner's instruction on 2026-09-07: the databases are production and nothing
// is dropped; InitialCreate is the baseline they are AT; every later change is its
// own `dotnet ef migrations add`. So a second migration is no longer a defect - it
// is the mechanism. What still has to be guarded is the merge hazard that pinning
// the id was invented to prevent, which is why this file did not simply go away.
using Xunit;

namespace SIMF.Domain.Tests;

public sealed class SchemaFreezeTests
{
    private const string MigrationsRoot =
        "src/Backend/SIMF.Infrastructure/Persistence/Migrations";

    // Not a timestamp, and deliberately not one: nothing about it invites a reader
    // to think it records when the schema was written. It sorts before every real
    // timestamp, so each delta migration applies after it, in the order added.
    private const string PinnedBaselineId = "00000000000000_InitialCreate";

    public static TheoryData<string> Contexts() => new() { "App", "Identity" };

    [Theory]
    [MemberData(nameof(Contexts))]
    public void Each_context_has_exactly_one_InitialCreate_and_its_id_is_pinned(string context)
    {
        // The baseline describes what the live databases already contain, so it is
        // the one migration that must never be regenerated or re-stamped: change
        // its id and every existing database's history row stops matching, and EF
        // tries to create a schema that is already there.
        var baselines = MigrationNames(context)
            .Where(name => name.EndsWith("_InitialCreate", StringComparison.Ordinal))
            .ToList();

        Assert.True(
            baselines.Count == 1,
            $"{context} has {baselines.Count} InitialCreate migrations: "
            + string.Join(", ", baselines)
            + ". There is exactly one baseline per context and it is the schema the "
            + "live databases are already at. A schema CHANGE is a new migration "
            + "added with `dotnet ef migrations add`, never a second baseline.");

        Assert.True(
            baselines[0] == PinnedBaselineId,
            $"The {context} baseline is '{baselines[0]}' but must be "
            + $"'{PinnedBaselineId}'. Existing databases - production included - "
            + "record that exact id in __EFMigrationsHistory. Re-stamping it makes "
            + "every one of them look un-migrated.");
    }

    [Theory]
    [MemberData(nameof(Contexts))]
    public void No_two_migrations_share_a_name_or_an_id(string context)
    {
        // THE MERGE HAZARD, which outlived the rule that used to guard it.
        //
        // `dotnet ef migrations add` stamps a fresh UTC timestamp, so two branches
        // that each add a migration write two DIFFERENT filenames. Git has nothing
        // to conflict on, both pull requests report a clean merge, and both files
        // land. That is now FINE when the two migrations are genuinely different
        // changes - which is the whole point of moving to incremental migrations.
        //
        // It is NOT fine when both branches chose the same migration NAME: the
        // class name comes from the name, not the timestamp, so main ends up with
        // two `public partial class SyncBaseline` in one namespace and stops
        // compiling. That is exactly how main broke twice on 2026-08-16, and no
        // gate on either pull request can see it, because neither is wrong alone.
        //
        // Renaming one of the two classes is the resolution. Regenerating is not:
        // a migration already applied to a live database cannot be re-minted.
        var names = MigrationNames(context).ToList();

        var duplicateClasses = names
            .Select(ClassNameOf)
            .GroupBy(name => name, StringComparer.Ordinal)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .ToList();

        Assert.True(
            duplicateClasses.Count == 0,
            $"{context} has migrations sharing a class name: "
            + string.Join(", ", duplicateClasses)
            + ". Two branches each ran `dotnet ef migrations add` with the same "
            + "name; the timestamps differ so git merged both cleanly, but the "
            + "generated classes collide in one namespace and the build fails. "
            + "Rename one class and its file - do NOT regenerate, because the "
            + "other migration may already be applied to a live database.");

        var duplicateIds = names
            .GroupBy(name => name, StringComparer.Ordinal)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .ToList();

        Assert.True(
            duplicateIds.Count == 0,
            $"{context} has duplicate migration ids: " + string.Join(", ", duplicateIds));
    }

    [Theory]
    [MemberData(nameof(Contexts))]
    public void Every_migration_filename_matches_the_id_EF_actually_reads(string context)
    {
        // The filename is convention; the [Migration("...")] attribute is what EF
        // writes to __EFMigrationsHistory and compares against on the next run.
        // They drift only when someone renames a file by hand - which is precisely
        // the moment it matters, because a migration whose recorded id does not
        // match any file on disk is one EF will silently try to apply again.
        var folder = FolderFor(context);

        foreach (var name in MigrationNames(context))
        {
            var designer = Path.Combine(folder, $"{name}.Designer.cs");

            Assert.True(
                File.Exists(designer),
                $"{context}/{name}.cs has no matching .Designer.cs. EF generates "
                + "both; a migration missing its designer half was hand-authored or "
                + "half-deleted.");

            Assert.Contains(
                $"[Migration(\"{name}\")]",
                File.ReadAllText(designer),
                StringComparison.Ordinal);
        }
    }

    [Fact]
    public void The_frozen_enum_surface_is_still_where_the_freeze_says_it_is()
    {
        // D-110 froze "every enum in src/Shared/SIMF.Common/Enums/" against rename
        // and reorder, and D-895 kept that when it re-instated the freeze. Moving
        // the directory would silently empty the rule, so its location is asserted
        // rather than assumed. The values themselves are not pinned here: additive
        // values are allowed, and pinning each one would fail on exactly the change
        // the freeze permits.
        var enums = Path.Combine(RepoRoot(), "src", "Shared", "SIMF.Common", "Enums");

        Assert.True(
            Directory.Exists(enums),
            $"The frozen enum surface is not at {enums}. CLAUDE.md's freeze names "
            + "that path; if the enums moved, the freeze text must move with them.");

        Assert.NotEmpty(Directory.EnumerateFiles(enums, "*.cs"));
    }

    // "20260907080012_SyncBaseline" -> "SyncBaseline". EF names the class after the
    // part following the first underscore, so that is what collides on a merge.
    private static string ClassNameOf(string migrationId)
    {
        var underscore = migrationId.IndexOf('_');
        return underscore < 0 ? migrationId : migrationId[(underscore + 1)..];
    }

    private static IEnumerable<string> MigrationNames(string context)
    {
        var folder = FolderFor(context);
        Assert.True(Directory.Exists(folder), $"Migrations folder missing: {folder}");

        // *.Designer.cs is the same migration's designer half, not a second
        // migration, so it is excluded rather than counted.
        return Directory
            .EnumerateFiles(folder, "*.cs")
            .Select(Path.GetFileNameWithoutExtension)
            .Where(name => name is not null
                && !name.EndsWith(".Designer", StringComparison.Ordinal)
                && !name.EndsWith("ModelSnapshot", StringComparison.Ordinal))
            .Select(name => name!)
            .OrderBy(name => name, StringComparer.Ordinal);
    }

    private static string FolderFor(string context) => Path.Combine(
        RepoRoot(), MigrationsRoot.Replace('/', Path.DirectorySeparatorChar), context);

    private static string RepoRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null
               && !File.Exists(Path.Combine(directory.FullName, "SIMF.slnx")))
        {
            directory = directory.Parent;
        }

        Assert.NotNull(directory);
        return directory!.FullName;
    }
}
