namespace SIMF.Application.Programme.Abstractions;

/// <summary>D-578 — the transcript a server-side fetch pulled from a video's captions.</summary>
/// <param name="Text">The cleaned running transcript text.</param>
/// <param name="LanguageCode">The caption track's BCP-47 language (e.g. "en", "ar").</param>
/// <param name="AutoGenerated">True when the track is YouTube's ASR auto-caption.</param>
public sealed record TranscriptResult(string Text, string LanguageCode, bool AutoGenerated);

/// <summary>
/// D-578 — fetches a video's caption transcript server-side so the CP Sessions
/// editor can auto-populate a session's subtitle (LiveCaptions) instead of the
/// admin pasting/uploading it. The proof-of-concept provider is YouTube. This path
/// only works where the API host has outbound access to YouTube; on a locked-down
/// network (the RSNF/NCA on-prem deployment blocks YouTube) it throws
/// <c>SUBTITLE_FETCH_FAILED</c> (502) and the caller falls back to paste/upload.
/// </summary>
public interface IYoutubeTranscriptService
{
    /// <summary>Fetches the transcript for a YouTube video URL.
    /// <paramref name="preferredLang"/> is a 2-letter hint ("ar"/"en") or null for the
    /// best available track. Throws <c>ApiException(SUBTITLE_FETCH_FAILED)</c> for a
    /// non-YouTube URL (400), a video with no captions (422), or when YouTube is
    /// unreachable / unparseable (502).</summary>
    Task<TranscriptResult> FetchAsync(
        string videoUrl, string? preferredLang, CancellationToken cancellationToken = default);
}
