import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart' show DateFormat;
import 'package:share_plus/share_plus.dart';
import 'package:simf_data_pkg/simf_data_pkg.dart';

import '../../app/localization/app_l10n.dart';
import '../../app/theme/tokens.dart';
import '../../app/widgets/ksa_shell.dart';
import '../sessions/data/session_models.dart';
import '../sessions/data/sessions_repository.dart';
import 'data/session_summary_models.dart';
import 'data/session_summary_repository.dart';

/// The programme list, reused for the "اختر الجلسة" picker
/// (`GET /app/programme/sessions`).
final aiSummarySessionsProvider =
    FutureProvider.autoDispose<List<SessionListItem>>(
  (ref) => ref.watch(sessionsRepositoryProvider).getSessions(),
);

/// Locale-data-free formatters (mirror `sessions_screen.dart`).
final DateFormat _time24 = DateFormat('HH:mm'); // 09:30
final DateFormat _timeRow = DateFormat('hh:mm a'); // 08:00 PM

const List<String> _weekdaysAr = <String>[
  'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت', 'الأحد',
];
const List<String> _weekdaysEn = <String>[
  'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday',
];

String _weekday(DateTime d, bool isArabic) =>
    (isArabic ? _weekdaysAr : _weekdaysEn)[d.weekday - 1];

/// The three summary tabs (frame `1072:14647`).
enum _SummaryTab { speakers, keyPoints, recommendations }

/// Page 034 — ملخص الجلسة · AI session summary (#34, `/ai-summary`).
///
/// **Public** (Guest+, `AllowAnonymous`). Pixel-parity to KSA Figma frame
/// `1072:13518`: the navy [KsaPage] shell, the "اختر الجلسة" session picker
/// (reuses the programme list), the "generated by AI" banner, the
/// المتحدثون / أبرز النقاط / التوصيات tabs (mapped to the published summary's
/// `speakers` / `keyPoints` / `recommendations`) and the
/// النص الكامل / مشاركة / حفظ action row. Opened with an optional `sessionId`
/// (preselected); otherwise the first programme session is selected. Reads the
/// published summary (`GET /app/programme/sessions/{id}/summary`); a 404 means
/// the session has no published summary yet.
class AiSummaryScreen extends ConsumerStatefulWidget {
  const AiSummaryScreen({this.sessionId, super.key});

  final String? sessionId;

  @override
  ConsumerState<AiSummaryScreen> createState() => _AiSummaryScreenState();
}

class _AiSummaryScreenState extends ConsumerState<AiSummaryScreen> {
  String? _selectedId;
  SessionListItem? _selectedSession;
  bool _loading = false;
  bool _error = false;
  bool _notFound = false;
  SessionSummary? _summary;
  _SummaryTab _tab = _SummaryTab.keyPoints;

  @override
  void initState() {
    super.initState();
    final id = widget.sessionId?.trim();
    if (id != null && id.isNotEmpty) {
      _selectedId = id;
      unawaited(_load());
    }
  }

  Future<void> _load() async {
    final id = _selectedId;
    if (id == null) {
      return;
    }
    setState(() {
      _loading = true;
      _error = false;
      _notFound = false;
    });
    try {
      final summary =
          await ref.read(sessionSummaryRepositoryProvider).getSummary(id);
      if (!mounted) {
        return;
      }
      setState(() {
        _summary = summary;
        _loading = false;
      });
    } on ApiFailure catch (failure) {
      if (!mounted) {
        return;
      }
      setState(() {
        _loading = false;
        _notFound = failure.httpStatus == 404;
        _error = failure.httpStatus != 404;
      });
    }
  }

  void _select(SessionListItem session) {
    if (session.id == _selectedId && _selectedSession != null) {
      return;
    }
    setState(() {
      _selectedId = session.id;
      _selectedSession = session;
    });
    unawaited(_load());
  }

  /// Preselect on first session load: the passed-in id (resolving its item) or
  /// the first session. Guarded so it only fires until a selection is resolved.
  void _ensureSelection(List<SessionListItem> sessions) {
    if (sessions.isEmpty || (_selectedId != null && _selectedSession != null)) {
      return;
    }
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted) {
        return;
      }
      if (_selectedId == null) {
        _select(sessions.first);
      } else if (_selectedSession == null) {
        final match = sessions.where((s) => s.id == _selectedId);
        if (match.isNotEmpty) {
          setState(() => _selectedSession = match.first);
        }
      }
    });
  }

  Future<void> _share(SessionSummary summary, bool isArabic) async {
    final text = <String>[
      if (_selectedSession != null) _selectedSession!.localizedTitle(isArabic),
      summary.localizedKeyPoints(isArabic),
      summary.localizedRecommendations(isArabic),
    ].where((p) => p.trim().isNotEmpty).join('\n\n');
    if (text.isEmpty) {
      return;
    }
    try {
      await Share.share(text);
    } catch (_) {
      // Sharing is best-effort (no share target / cancelled) — ignore.
    }
  }

  void _save(AppL10n l10n) {
    ScaffoldMessenger.of(context)
      ..hideCurrentSnackBar()
      ..showSnackBar(SnackBar(content: Text(l10n.aiSummarySaved)));
  }

  void _showFullText(AppL10n l10n, String text) {
    showModalBottomSheet<void>(
      context: context,
      backgroundColor: SimfTokens.navyDeep,
      showDragHandle: true,
      isScrollControlled: true,
      builder: (_) => SafeArea(
        child: Padding(
          padding: const EdgeInsets.fromLTRB(
            SimfTokens.space4,
            0,
            SimfTokens.space4,
            SimfTokens.space6,
          ),
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                _SectionHeading(l10n.aiSummaryFullTextHeading),
                const SizedBox(height: SimfTokens.space3),
                Text(
                  text.trim().isEmpty ? l10n.aiSummaryNone : text,
                  style: const TextStyle(
                    color: SimfTokens.txtSecondary,
                    height: 1.75,
                    fontSize: SimfTokens.textSm,
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppL10n.of(context);
    final sessions = ref.watch(aiSummarySessionsProvider);
    return KsaPage(
      title: l10n.aiSummaryTitle,
      onBack: () => ksaBackOrHome(context),
      body: ListView(
        padding: const EdgeInsets.all(SimfTokens.space4),
        children: <Widget>[
          sessions.when(
            loading: () => const _PickerLoading(),
            error: (_, __) => _Inline(
              icon: Icons.event_busy_outlined,
              message: l10n.aiSummaryNoSessions,
            ),
            data: (list) {
              if (list.isEmpty) {
                return _Inline(
                  icon: Icons.event_busy_outlined,
                  message: l10n.aiSummaryNoSessions,
                );
              }
              _ensureSelection(list);
              return _SessionPicker(
                title: l10n.aiSummaryChooseSession,
                sessions: list,
                selectedId: _selectedId,
                isArabic: l10n.isArabic,
                onSelect: _select,
              );
            },
          ),
          const SizedBox(height: SimfTokens.space4),
          ..._summaryArea(l10n),
        ],
      ),
    );
  }

  List<Widget> _summaryArea(AppL10n l10n) {
    if (_selectedId == null) {
      return const <Widget>[];
    }
    if (_loading) {
      return const <Widget>[
        Padding(
          padding: EdgeInsets.symmetric(vertical: SimfTokens.space8),
          child: Center(child: CircularProgressIndicator()),
        ),
      ];
    }
    if (_notFound) {
      return <Widget>[
        _Inline(icon: Icons.summarize_outlined, message: l10n.aiSummaryNone),
      ];
    }
    if (_error || _summary == null) {
      return <Widget>[
        _ErrorInline(
          message: l10n.aiSummaryError,
          onRetry: () => unawaited(_load()),
        ),
      ];
    }
    return _content(l10n, _summary!);
  }

  List<Widget> _content(AppL10n l10n, SessionSummary summary) {
    final isArabic = l10n.isArabic;
    final session = _selectedSession;
    final block = switch (_tab) {
      _SummaryTab.speakers => summary.localizedSpeakers(isArabic),
      _SummaryTab.keyPoints => summary.localizedKeyPoints(isArabic),
      _SummaryTab.recommendations => summary.localizedRecommendations(isArabic),
    };
    final tabTitle = switch (_tab) {
      _SummaryTab.speakers => l10n.aiSummarySpeakersHeading,
      _SummaryTab.keyPoints => l10n.aiSummaryKeyPointsHeading,
      _SummaryTab.recommendations => l10n.aiSummaryRecommendationsHeading,
    };
    return <Widget>[
      if (summary.generatedByAi) ...<Widget>[
        _AiBanner(
          label: l10n.aiSummaryGeneratedBanner,
          subtitle: session == null
              ? null
              : '${session.localizedTitle(isArabic)} · '
                  '${_time24.format(session.startLocal)}',
        ),
        const SizedBox(height: SimfTokens.space4),
      ],
      _Tabs(active: _tab, l10n: l10n, onChanged: (t) => setState(() => _tab = t)),
      const SizedBox(height: SimfTokens.space4),
      _ContentCard(title: tabTitle, block: block, emptyLabel: l10n.aiSummaryNone),
      const SizedBox(height: SimfTokens.space4),
      _ActionRow(
        l10n: l10n,
        onFullText: () =>
            _showFullText(l10n, summary.localizedFullText(isArabic)),
        onShare: () => unawaited(_share(summary, isArabic)),
        onSave: () => _save(l10n),
      ),
    ];
  }
}

/// The "اختر الجلسة" picker (frame `1072:14628`): the title, a bordered
/// selected-session box (with the collapse chevron) and, when expanded, the
/// tappable session list.
class _SessionPicker extends StatefulWidget {
  const _SessionPicker({
    required this.title,
    required this.sessions,
    required this.selectedId,
    required this.isArabic,
    required this.onSelect,
  });

  final String title;
  final List<SessionListItem> sessions;
  final String? selectedId;
  final bool isArabic;
  final ValueChanged<SessionListItem> onSelect;

  @override
  State<_SessionPicker> createState() => _SessionPickerState();
}

class _SessionPickerState extends State<_SessionPicker> {
  bool _expanded = true;

  @override
  Widget build(BuildContext context) {
    final sessions = widget.sessions;
    final selected = sessions.where((s) => s.id == widget.selectedId);
    final current = selected.isNotEmpty ? selected.first : null;
    return Container(
      padding: const EdgeInsets.all(SimfTokens.space4),
      decoration: BoxDecoration(
        color: SimfTokens.navyDeep,
        borderRadius: BorderRadius.circular(SimfTokens.radius),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Text(
            widget.title,
            style: const TextStyle(
              color: Colors.white,
              fontSize: SimfTokens.textLg,
              fontWeight: FontWeight.w500,
            ),
          ),
          const SizedBox(height: SimfTokens.space3),
          if (current != null)
            _SelectedSessionBox(
              session: current,
              isArabic: widget.isArabic,
              expanded: _expanded,
              onToggle: () => setState(() => _expanded = !_expanded),
            ),
          if (_expanded) ...<Widget>[
            const SizedBox(height: SimfTokens.space2),
            for (final session in sessions)
              _SessionRow(
                session: session,
                selected: session.id == widget.selectedId,
                isArabic: widget.isArabic,
                onTap: () => widget.onSelect(session),
              ),
          ],
        ],
      ),
    );
  }
}

/// The highlighted selected-session box (frame `1072:14603`): beige hairline,
/// the collapse chevron, the gold title and the day · time · hall sub-line.
class _SelectedSessionBox extends StatelessWidget {
  const _SelectedSessionBox({
    required this.session,
    required this.isArabic,
    required this.expanded,
    required this.onToggle,
  });

  final SessionListItem session;
  final bool isArabic;
  final bool expanded;
  final VoidCallback onToggle;

  @override
  Widget build(BuildContext context) {
    final hall = session.localizedHall(isArabic);
    final sub = <String>[
      _weekday(session.startLocal, isArabic),
      _time24.format(session.startLocal),
      if (hall != null && hall.trim().isNotEmpty) hall,
    ].join(' · ');
    return InkWell(
      onTap: onToggle,
      borderRadius: BorderRadius.circular(SimfTokens.radiusSmall),
      child: Container(
        padding: const EdgeInsets.symmetric(
          horizontal: SimfTokens.space3,
          vertical: SimfTokens.space3,
        ),
        decoration: BoxDecoration(
          border: Border.all(
            color: SimfTokens.beigeBorder,
            width: SimfTokens.hairline,
          ),
          borderRadius: BorderRadius.circular(SimfTokens.radiusSmall),
        ),
        child: Row(
          children: <Widget>[
            Icon(
              expanded ? Icons.expand_less : Icons.expand_more,
              color: SimfTokens.accent,
              size: 20,
            ),
            const SizedBox(width: SimfTokens.space2),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Text(
                    session.localizedTitle(isArabic),
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                    style: const TextStyle(
                      color: SimfTokens.accent,
                      fontSize: SimfTokens.textMd,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                  const SizedBox(height: SimfTokens.space1),
                  Text(
                    sub,
                    style: const TextStyle(
                      color: SimfTokens.beigeBorder,
                      fontSize: SimfTokens.textSm,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// One selectable session row (frames `1072:14612`…): the time at the inline
/// start, the title at the inline end; the selected row is gold.
class _SessionRow extends StatelessWidget {
  const _SessionRow({
    required this.session,
    required this.selected,
    required this.isArabic,
    required this.onTap,
  });

  final SessionListItem session;
  final bool selected;
  final bool isArabic;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final color = selected ? SimfTokens.accent : Colors.white;
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(SimfTokens.radiusSmall),
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: SimfTokens.space3),
        child: Row(
          children: <Widget>[
            Text(
              _timeRow.format(session.startLocal),
              textDirection: TextDirection.ltr,
              style: TextStyle(
                color: SimfTokens.beigeBorder,
                fontSize: SimfTokens.textSm,
              ),
            ),
            const SizedBox(width: SimfTokens.space3),
            Expanded(
              child: Text(
                session.localizedTitle(isArabic),
                textAlign: TextAlign.end,
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
                style: TextStyle(
                  color: color,
                  fontSize: SimfTokens.textMd,
                  fontWeight: selected ? FontWeight.w700 : FontWeight.w500,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

/// The "generated by AI" banner (frame `1072:14629`): the gold label over the
/// session sub-line, a leading sparkle and a trailing gold "AI" square.
class _AiBanner extends StatelessWidget {
  const _AiBanner({required this.label, this.subtitle});

  final String label;
  final String? subtitle;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(
        horizontal: SimfTokens.space4,
        vertical: SimfTokens.space3,
      ),
      decoration: BoxDecoration(
        color: SimfTokens.navyDeep,
        border: Border.all(
          color: SimfTokens.beigeBorder,
          width: SimfTokens.hairline,
        ),
        borderRadius: BorderRadius.circular(SimfTokens.radius),
      ),
      child: Row(
        children: <Widget>[
          Container(
            width: 36,
            height: 36,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              color: SimfTokens.accent,
              borderRadius: BorderRadius.circular(SimfTokens.radiusSmall),
            ),
            child: const Text(
              'AI',
              style: TextStyle(
                color: Colors.white,
                fontSize: SimfTokens.textMd,
                fontWeight: FontWeight.w700,
              ),
            ),
          ),
          const SizedBox(width: SimfTokens.space3),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Text(
                  label,
                  style: const TextStyle(
                    color: SimfTokens.accent,
                    fontSize: SimfTokens.textMd,
                    fontWeight: FontWeight.w600,
                  ),
                ),
                if (subtitle != null && subtitle!.trim().isNotEmpty) ...<Widget>[
                  const SizedBox(height: SimfTokens.space1),
                  Text(
                    subtitle!,
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    style: const TextStyle(
                      color: SimfTokens.beigeBorder,
                      fontSize: SimfTokens.textSm,
                    ),
                  ),
                ],
              ],
            ),
          ),
          const SizedBox(width: SimfTokens.space3),
          const Icon(Icons.auto_awesome, color: SimfTokens.accent, size: 16),
        ],
      ),
    );
  }
}

/// The three tabs (frame `1072:14647`): active = gold fill, others = beige
/// hairline. Order (reading) speakers · key-points · recommendations.
class _Tabs extends StatelessWidget {
  const _Tabs({required this.active, required this.l10n, required this.onChanged});

  final _SummaryTab active;
  final AppL10n l10n;
  final ValueChanged<_SummaryTab> onChanged;

  @override
  Widget build(BuildContext context) {
    final tabs = <(_SummaryTab, String)>[
      (_SummaryTab.speakers, l10n.aiSummarySpeakersHeading),
      (_SummaryTab.keyPoints, l10n.aiSummaryKeyPointsHeading),
      (_SummaryTab.recommendations, l10n.aiSummaryRecommendationsHeading),
    ];
    return Row(
      children: <Widget>[
        for (final (index, (tab, label)) in tabs.indexed) ...<Widget>[
          if (index > 0) const SizedBox(width: SimfTokens.space2),
          Expanded(
            child: _PillButton(
              label: label,
              filled: tab == active,
              fontWeight:
                  tab == active ? FontWeight.w700 : FontWeight.w500,
              onTap: () => onChanged(tab),
            ),
          ),
        ],
      ],
    );
  }
}

/// A full-width pill — gold fill when [filled], else a beige hairline outline.
/// Shared by the summary tabs (frame `1072:14647`) and the action row (frame
/// `1075:14677`).
class _PillButton extends StatelessWidget {
  const _PillButton({
    required this.label,
    required this.filled,
    required this.onTap,
    this.fontWeight = FontWeight.w600,
  });

  final String label;
  final bool filled;
  final VoidCallback onTap;
  final FontWeight fontWeight;

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(SimfTokens.radius),
      child: Container(
        height: 40,
        alignment: Alignment.center,
        decoration: BoxDecoration(
          color: filled ? SimfTokens.accent : Colors.transparent,
          border: filled
              ? null
              : Border.all(
                  color: SimfTokens.beigeBorder,
                  width: SimfTokens.hairline,
                ),
          borderRadius: BorderRadius.circular(SimfTokens.radius),
        ),
        child: Text(
          label,
          maxLines: 1,
          overflow: TextOverflow.ellipsis,
          style: TextStyle(
            color: filled ? Colors.white : SimfTokens.beigeBorder,
            fontSize: SimfTokens.textSm,
            fontWeight: fontWeight,
          ),
        ),
      ),
    );
  }
}

/// The active-tab content card (frame `1072:14673`): a gold-bar heading and the
/// block rendered as bullets (multi-line) or a paragraph (single line).
class _ContentCard extends StatelessWidget {
  const _ContentCard({
    required this.title,
    required this.block,
    required this.emptyLabel,
  });

  final String title;
  final String block;
  final String emptyLabel;

  @override
  Widget build(BuildContext context) {
    final lines = block
        .split('\n')
        .map((l) => l.trim())
        .where((l) => l.isNotEmpty)
        .toList(growable: false);
    return Container(
      padding: const EdgeInsets.all(SimfTokens.space4),
      decoration: BoxDecoration(
        color: SimfTokens.navyDeep,
        borderRadius: BorderRadius.circular(SimfTokens.radius),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          _SectionHeading(title),
          const SizedBox(height: SimfTokens.space3),
          if (lines.isEmpty)
            _Body(emptyLabel)
          else if (lines.length == 1)
            _Body(lines.first)
          else
            for (final point in lines) _Bullet(text: point),
        ],
      ),
    );
  }
}

/// The action row (frame `1075:14677`): full-text + share (outlined) and save
/// (gold). Reading order: full-text · share · save.
class _ActionRow extends StatelessWidget {
  const _ActionRow({
    required this.l10n,
    required this.onFullText,
    required this.onShare,
    required this.onSave,
  });

  final AppL10n l10n;
  final VoidCallback onFullText;
  final VoidCallback onShare;
  final VoidCallback onSave;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: <Widget>[
        Expanded(
          child: _PillButton(
            label: l10n.aiSummaryFullTextHeading,
            filled: false,
            onTap: onFullText,
          ),
        ),
        const SizedBox(width: SimfTokens.space2),
        Expanded(
          child: _PillButton(
            label: l10n.aiSummaryShare,
            filled: false,
            onTap: onShare,
          ),
        ),
        const SizedBox(width: SimfTokens.space2),
        Expanded(
          child: _PillButton(
            label: l10n.aiSummarySave,
            filled: true,
            onTap: onSave,
          ),
        ),
      ],
    );
  }
}

/// A section title (frame `1072:14660`): a short gold bar + the white heading.
class _SectionHeading extends StatelessWidget {
  const _SectionHeading(this.text);

  final String text;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: <Widget>[
        Container(
          width: 4,
          height: 16,
          decoration: BoxDecoration(
            color: SimfTokens.accent,
            borderRadius: BorderRadius.circular(2),
          ),
        ),
        const SizedBox(width: SimfTokens.space2),
        Expanded(
          child: Text(
            text,
            style: const TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.w700,
              fontSize: SimfTokens.textMd,
            ),
          ),
        ),
      ],
    );
  }
}

/// One bullet row (frame `1072:14666`): a gold dot and the point text.
class _Bullet extends StatelessWidget {
  const _Bullet({required this.text});

  final String text;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: SimfTokens.space3),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const Padding(
            padding: EdgeInsets.only(top: SimfTokens.space1 + 2),
            child: Icon(Icons.circle, size: 5, color: SimfTokens.accent),
          ),
          const SizedBox(width: SimfTokens.space2),
          Expanded(
            child: Text(
              text,
              style: const TextStyle(
                color: SimfTokens.txtSecondary,
                height: 1.6,
                fontSize: SimfTokens.textSm,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _Body extends StatelessWidget {
  const _Body(this.text);

  final String text;

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: const TextStyle(
        color: SimfTokens.txtSecondary,
        height: 1.75,
        fontSize: SimfTokens.textSm,
      ),
    );
  }
}

class _PickerLoading extends StatelessWidget {
  const _PickerLoading();

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.symmetric(vertical: SimfTokens.space8),
      child: Center(child: CircularProgressIndicator()),
    );
  }
}

class _Inline extends StatelessWidget {
  const _Inline({required this.icon, required this.message});

  final IconData icon;
  final String message;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: SimfTokens.space8),
      child: Column(
        children: <Widget>[
          Icon(icon, size: 56, color: SimfTokens.txtTertiary),
          const SizedBox(height: SimfTokens.space3),
          Text(
            message,
            textAlign: TextAlign.center,
            style: const TextStyle(color: SimfTokens.txtSecondary),
          ),
        ],
      ),
    );
  }
}

class _ErrorInline extends StatelessWidget {
  const _ErrorInline({required this.message, required this.onRetry});

  final String message;
  final VoidCallback onRetry;

  @override
  Widget build(BuildContext context) {
    final l10n = AppL10n.of(context);
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: SimfTokens.space6),
      child: Column(
        children: <Widget>[
          Text(
            message,
            textAlign: TextAlign.center,
            style: const TextStyle(color: SimfTokens.txtSecondary),
          ),
          const SizedBox(height: SimfTokens.space4),
          FilledButton(onPressed: onRetry, child: Text(l10n.retryLabel)),
        ],
      ),
    );
  }
}
