import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:simf_data_pkg/simf_data_pkg.dart';

import '../../app/localization/app_l10n.dart';
import '../../app/theme/tokens.dart';
import '../../app/widgets/ksa_shell.dart';
import 'data/session_summary_models.dart';
import 'data/session_summary_repository.dart';

/// Page 034 — ملخص الجلسة · AI session summary (#34, `/ai-summary`).
///
/// **Public** (Guest+, `AllowAnonymous`). Opened from a session with an optional
/// `sessionId` query parameter. With **no** id the screen shows a neutral
/// "open a summary from a session" state and never fetches. With an id it reads
/// the published summary (`GET /app/programme/sessions/{id}/summary`) and renders
/// the present sections — a "generated by AI" banner, Key points (bullets),
/// Recommendations, Speakers and Full text. A 404 means the session has no
/// published summary yet; any other failure offers a retry. UI is interim
/// (final visuals from SIMF-VID-001).
class AiSummaryScreen extends ConsumerStatefulWidget {
  const AiSummaryScreen({this.sessionId, super.key});

  final String? sessionId;

  @override
  ConsumerState<AiSummaryScreen> createState() => _AiSummaryScreenState();
}

class _AiSummaryScreenState extends ConsumerState<AiSummaryScreen> {
  bool _loading = false;
  bool _error = false;
  bool _notFound = false;
  SessionSummary? _summary;

  bool get _hasId =>
      widget.sessionId != null && widget.sessionId!.trim().isNotEmpty;

  @override
  void initState() {
    super.initState();
    if (_hasId) {
      unawaited(_load());
    }
  }

  Future<void> _load() async {
    setState(() {
      _loading = true;
      _error = false;
      _notFound = false;
    });
    try {
      final repo = ref.read(sessionSummaryRepositoryProvider);
      final summary = await repo.getSummary(widget.sessionId!.trim());
      if (!mounted) {
        return;
      }
      setState(() {
        _summary = summary;
        _loading = false;
      });
    } on ApiFailure catch (failure) {
      if (!mounted) {
        return;
      }
      setState(() {
        _loading = false;
        _notFound = failure.httpStatus == 404;
        _error = failure.httpStatus != 404;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppL10n.of(context);
    return Scaffold(
      appBar: AppBar(leading: const SimfBackButton(), title: Text(l10n.aiSummaryTitle)),
      body: SafeArea(child: _buildBody(l10n)),
    );
  }

  Widget _buildBody(AppL10n l10n) {
    if (!_hasId) {
      return _EmptyState(
        icon: Icons.auto_awesome_outlined,
        message: l10n.aiSummaryOpenFromSession,
      );
    }
    if (_loading) {
      return const Center(child: CircularProgressIndicator());
    }
    if (_notFound) {
      return _EmptyState(
        icon: Icons.summarize_outlined,
        message: l10n.aiSummaryNone,
      );
    }
    if (_error || _summary == null) {
      return _ErrorState(
        message: l10n.aiSummaryError,
        onRetry: () => unawaited(_load()),
      );
    }
    return _content(l10n, _summary!);
  }

  Widget _content(AppL10n l10n, SessionSummary summary) {
    final isArabic = l10n.isArabic;
    final keyPoints = summary.keyPointsLines(isArabic);
    final recommendations = summary.localizedRecommendations(isArabic);
    final speakers = summary.localizedSpeakers(isArabic);
    final fullText = summary.localizedFullText(isArabic);

    return ListView(
      padding: const EdgeInsets.fromLTRB(
        SimfTokens.space4,
        SimfTokens.space4,
        SimfTokens.space4,
        SimfTokens.space6,
      ),
      children: <Widget>[
        if (summary.generatedByAi) ...<Widget>[
          _AiBanner(label: l10n.aiSummaryGeneratedBanner),
          const SizedBox(height: SimfTokens.space3),
        ],
        if (keyPoints.isNotEmpty) ...<Widget>[
          _SummarySection(
            title: l10n.aiSummaryKeyPointsHeading,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                for (final point in keyPoints) _Bullet(text: point),
              ],
            ),
          ),
          const SizedBox(height: SimfTokens.space3),
        ],
        if (recommendations.isNotEmpty) ...<Widget>[
          _SummarySection(
            title: l10n.aiSummaryRecommendationsHeading,
            child: _Body(recommendations),
          ),
          const SizedBox(height: SimfTokens.space3),
        ],
        if (speakers.isNotEmpty) ...<Widget>[
          _SummarySection(
            title: l10n.aiSummarySpeakersHeading,
            child: _Body(speakers),
          ),
          const SizedBox(height: SimfTokens.space3),
        ],
        if (fullText.isNotEmpty) ...<Widget>[
          _SummarySection(
            title: l10n.aiSummaryFullTextHeading,
            child: _Body(fullText),
          ),
        ],
      ],
    );
  }
}

/// The "generated by AI" notice band shown above the sections (mockup
/// `.ai-banner`): a gold-tinted card with a solid "AI" tag pill and the title.
class _AiBanner extends StatelessWidget {
  const _AiBanner({required this.label});

  final String label;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(
        horizontal: SimfTokens.space3,
        vertical: SimfTokens.space3,
      ),
      decoration: BoxDecoration(
        color: SimfTokens.accent.withValues(alpha: 0.08),
        border: Border.all(color: SimfTokens.accent.withValues(alpha: 0.30)),
        borderRadius: BorderRadius.circular(SimfTokens.radius),
      ),
      child: Row(
        children: <Widget>[
          Container(
            padding: const EdgeInsets.symmetric(
              horizontal: SimfTokens.space2,
              vertical: 3,
            ),
            decoration: BoxDecoration(
              color: SimfTokens.accent,
              borderRadius: BorderRadius.circular(SimfTokens.radiusSmall),
            ),
            child: const Text(
              'AI',
              style: TextStyle(
                color: SimfTokens.navy,
                fontSize: 9,
                fontWeight: FontWeight.w700,
                letterSpacing: 0.6,
              ),
            ),
          ),
          const SizedBox(width: SimfTokens.space3),
          Expanded(
            child: Text(
              label,
              style: const TextStyle(
                color: SimfTokens.surface,
                fontSize: SimfTokens.textSm,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// One summary block (mockup `.sum-section`): a card with a gold-bar heading
/// and the section body.
class _SummarySection extends StatelessWidget {
  const _SummarySection({required this.title, required this.child});

  final String title;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.symmetric(
          horizontal: SimfTokens.space4,
          vertical: SimfTokens.space3,
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            _SectionHeading(title),
            const SizedBox(height: SimfTokens.space2),
            child,
          ],
        ),
      ),
    );
  }
}

/// Section body copy (mockup `.sum-section p`): secondary white with a relaxed
/// line height.
class _Body extends StatelessWidget {
  const _Body(this.text);

  final String text;

  @override
  Widget build(BuildContext context) {
    return Text(
      text,
      style: const TextStyle(
        color: SimfTokens.txtSecondary,
        height: 1.75,
        fontSize: SimfTokens.textSm,
      ),
    );
  }
}

/// A section title (mockup `.sum-section h5`): a short gold bar followed by the
/// white bold heading text.
class _SectionHeading extends StatelessWidget {
  const _SectionHeading(this.text);

  final String text;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: <Widget>[
        Container(
          width: 4,
          height: 14,
          decoration: BoxDecoration(
            color: SimfTokens.accent,
            borderRadius: BorderRadius.circular(2),
          ),
        ),
        const SizedBox(width: SimfTokens.space2),
        Expanded(
          child: Text(
            text,
            style: const TextStyle(
              color: SimfTokens.surface,
              fontWeight: FontWeight.w700,
              fontSize: SimfTokens.textSm,
            ),
          ),
        ),
      ],
    );
  }
}

/// One key-point bullet row (mockup `.sum-section .pt`): a gold dot and the
/// secondary-white point text.
class _Bullet extends StatelessWidget {
  const _Bullet({required this.text});

  final String text;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: SimfTokens.space2),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          const Padding(
            padding: EdgeInsets.only(top: SimfTokens.space1 + 2),
            child: Icon(
              Icons.circle,
              size: 5,
              color: SimfTokens.accent,
            ),
          ),
          const SizedBox(width: SimfTokens.space2),
          Expanded(
            child: Text(
              text,
              style: const TextStyle(
                color: SimfTokens.txtSecondary,
                height: 1.6,
                fontSize: SimfTokens.textSm,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _EmptyState extends StatelessWidget {
  const _EmptyState({required this.icon, required this.message});

  final IconData icon;
  final String message;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(SimfTokens.space6),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Icon(icon, size: 56, color: SimfTokens.txtTertiary),
            const SizedBox(height: SimfTokens.space3),
            Text(
              message,
              textAlign: TextAlign.center,
              style: const TextStyle(color: SimfTokens.txtSecondary),
            ),
          ],
        ),
      ),
    );
  }
}

class _ErrorState extends StatelessWidget {
  const _ErrorState({required this.message, required this.onRetry});

  final String message;
  final VoidCallback onRetry;

  @override
  Widget build(BuildContext context) {
    final l10n = AppL10n.of(context);
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(SimfTokens.space6),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: <Widget>[
            Text(message, textAlign: TextAlign.center),
            const SizedBox(height: SimfTokens.space4),
            FilledButton(onPressed: onRetry, child: Text(l10n.retryLabel)),
          ],
        ),
      ),
    );
  }
}
