// D-578 — unit tests for the server-side YouTube transcript fetch. A stub
// HttpMessageHandler feeds canned innertube + timedtext JSON, so no network is hit
// (the real endpoint is unreachable on the locked-down network anyway).
using System.Net;
using System.Text;
using Microsoft.Extensions.Logging.Abstractions;
using SIMF.Common;
using SIMF.Infrastructure.Programme;
using Xunit;

namespace SIMF.Api.Tests;

[Trait(TestAreas.TraitName, TestAreas.Ai)]
[Trait(TestAreas.SpeedTraitName, TestAreas.Fast)]
public sealed class YoutubeTranscriptServiceTests
{
    private const string ValidUrl = "https://www.youtube.com/watch?v=dQw4w9WgXcQ";

    private static YoutubeTranscriptService Build(
        Func<HttpRequestMessage, HttpResponseMessage> responder) =>
        new(new HttpClient(new StubHandler(responder)),
            NullLogger<YoutubeTranscriptService>.Instance);

    private static HttpResponseMessage Json(string body) =>
        new(HttpStatusCode.OK)
        {
            Content = new StringContent(body, Encoding.UTF8, "application/json"),
        };

    [Fact]
    public async Task Fetches_and_flattens_the_caption_track()
    {
        const string player =
            "{\"captions\":{\"playerCaptionsTracklistRenderer\":{\"captionTracks\":["
            + "{\"baseUrl\":\"https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en\","
            + "\"languageCode\":\"en\",\"kind\":\"asr\"}]}}}";
        const string json3 =
            "{\"events\":["
            + "{\"segs\":[{\"utf8\":\"Good morning\"},{\"utf8\":\" everyone\"}]},"
            + "{\"segs\":[{\"utf8\":\"welcome to the forum\"}]}]}";

        var service = Build(req =>
            req.RequestUri!.AbsoluteUri.Contains("/youtubei/v1/player", StringComparison.Ordinal)
                ? Json(player)
                : Json(json3));

        var result = await service.FetchAsync(ValidUrl, "en");

        Assert.Equal("Good morning everyone welcome to the forum", result.Text);
        Assert.Equal("en", result.LanguageCode);
        Assert.True(result.AutoGenerated);
    }

    [Fact]
    public async Task Rejects_a_non_youtube_url_with_400()
    {
        var service = Build(_ => Json("{}"));

        var ex = await Assert.ThrowsAsync<ApiException>(
            () => service.FetchAsync("https://example.com/video.mp4", null));

        Assert.Equal(ErrorCodes.SubtitleFetchFailed, ex.Code);
        Assert.Equal(400, ex.StatusCode);
    }

    [Fact]
    public async Task Reports_422_when_the_video_has_no_captions()
    {
        var service = Build(_ => Json(
            "{\"captions\":{\"playerCaptionsTracklistRenderer\":{\"captionTracks\":[]}}}"));

        var ex = await Assert.ThrowsAsync<ApiException>(
            () => service.FetchAsync(ValidUrl, null));

        Assert.Equal(ErrorCodes.SubtitleFetchFailed, ex.Code);
        Assert.Equal(422, ex.StatusCode);
    }

    [Fact]
    public async Task Reports_502_when_youtube_is_unreachable()
    {
        var service = Build(_ => throw new HttpRequestException("blocked"));

        var ex = await Assert.ThrowsAsync<ApiException>(
            () => service.FetchAsync(ValidUrl, null));

        Assert.Equal(ErrorCodes.SubtitleFetchFailed, ex.Code);
        Assert.Equal(502, ex.StatusCode);
    }

    // An admin who presses Fetch subtitle and then navigates away cancels the
    // request. That is a routine client abort, not the missing-YouTube-egress
    // outage the catch-all reports, so it must propagate as a cancellation instead
    // of being logged and returned as a 502 that sends the on-call after a firewall
    // problem that does not exist.
    [Fact]
    public async Task Caller_cancellation_propagates_instead_of_reporting_an_outage()
    {
        var service = Build(_ => Json("{}"));
        using var aborted = new CancellationTokenSource();
        await aborted.CancelAsync();

        await Assert.ThrowsAnyAsync<OperationCanceledException>(
            () => service.FetchAsync(ValidUrl, null, aborted.Token));
    }

    // The other half of the same guard: the client's own 30-second timeout arrives
    // as the SAME exception type with the caller's token untouched, and IS a failed
    // fetch — so it must still funnel to the one bilingual 502.
    [Fact]
    public async Task A_client_timeout_still_reports_502()
    {
        var service = Build(_ => throw new TaskCanceledException("timed out"));

        var ex = await Assert.ThrowsAsync<ApiException>(
            () => service.FetchAsync(ValidUrl, null));

        Assert.Equal(ErrorCodes.SubtitleFetchFailed, ex.Code);
        Assert.Equal(502, ex.StatusCode);
    }

    private sealed class StubHandler(Func<HttpRequestMessage, HttpResponseMessage> responder)
        : HttpMessageHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(
            HttpRequestMessage request, CancellationToken cancellationToken) =>
            Task.FromResult(responder(request));
    }
}
