// Tests: SIMF.Api.Tests/YoutubeTranscriptServiceTests.cs (the service this wraps);
//        endpoint auth-gate (401) + graceful 502 path live-verified on dev.
//        A WebApplicationFactory integration test is deferred: this branch's host-boot
//        env issue (FileStorage/Region) fails all host-based API tests.
using FastEndpoints;
using SIMF.Application.Programme.Abstractions;
using SIMF.Common;
using SIMF.Contracts.Admin;

namespace SIMF.Api.Endpoints.Admin;

/// <summary>Server-side subtitle fetch from a video (YouTube) for the CP
/// Sessions editor. Stateless: it returns the transcript text so the admin reviews it
/// and Saves it onto the session's <c>LiveCaptions</c> (the AI session-summary drafter
/// then reads it). Gated by <c>Sessions.Edit</c> — the same permission that edits the
/// session's caption fields — on top of RequireApprovedAccount, and rate-limited.
/// Where the API host has no YouTube egress (the on-prem NCA network), the service
/// throws <c>SUBTITLE_FETCH_FAILED</c> (502) and the CP tells the admin to paste/upload
/// the subtitle instead.</summary>
public sealed class FetchSessionSubtitleEndpoint(IYoutubeTranscriptService transcripts)
    : Endpoint<FetchSubtitleRequest, ApiResult<FetchSubtitleResponse>>
{
    public override void Configure()
    {
        Post("/admin/sessions/subtitle/fetch-from-video");
        Policies(
            PermissionCatalog.PolicyFor(PermissionCatalog.Sessions.Edit),
            nameof(AuthorizationPolicies.RequireApprovedAccount));
        Options(rb => rb.RequireRateLimiting("auth"));
        Tags("Admin");
    }

    public override async Task HandleAsync(FetchSubtitleRequest req, CancellationToken ct)
    {
        var result = await transcripts.FetchAsync(req.VideoUrl, req.Lang, ct);
        await Send.OkAsync(
            ApiResult<FetchSubtitleResponse>.Ok(
                new FetchSubtitleResponse(result.Text, result.LanguageCode, result.AutoGenerated)),
            ct);
    }
}
