import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:go_router/go_router.dart';
import 'package:simf_app/app/localization/app_l10n.dart';
import 'package:simf_app/features/ai_summary/data/session_summary_models.dart';
import 'package:simf_app/features/ai_summary/data/session_summary_repository.dart';
import 'package:simf_app/features/ai_summary/session_summary_screen.dart';
import 'package:simf_data_pkg/simf_data_pkg.dart';

SessionSummary _summary() => SessionSummary.fromJson(const <String, dynamic>{
      'keyPoints': 'Coral cover rising\nNew survey method',
      'keyPointsArabic': 'تحسن الغطاء المرجاني\nأسلوب مسح جديد',
      'recommendations': 'Scale the reef programme',
      'recommendationsArabic': 'توسيع برنامج الشعاب',
      'speakers': 'Dr Reef, Cmdr Tide',
      'speakersArabic': 'د. ريف، العميد تايد',
      'fullText': 'The session covered reef restoration progress.',
      'fullTextArabic': 'تناولت الجلسة تقدم استعادة الشعاب.',
      'generatedByAi': true,
      'publishedAt': '2026-11-23T07:30:00Z',
    });

class _FakeSummaryRepo implements SessionSummaryRepository {
  _FakeSummaryRepo({this.summary, this.status});

  final SessionSummary? summary;
  final int? status;
  int calls = 0;

  @override
  Future<SessionSummary> getSummary(String sessionId) async {
    calls++;
    if (status != null) {
      throw ApiFailure(
        code: ApiErrorCodes.clientNetwork,
        message: 'x',
        httpStatus: status,
      );
    }
    return summary!;
  }
}

Future<void> _pump(
  WidgetTester tester, {
  required SessionSummaryRepository repo,
  String? sessionId,
  Locale locale = const Locale('en'),
}) async {
  final router = GoRouter(
    initialLocation: '/ai-summary',
    routes: <RouteBase>[
      GoRoute(
        path: '/ai-summary',
        builder: (_, __) => AiSummaryScreen(sessionId: sessionId),
      ),
    ],
  );

  await tester.pumpWidget(
    ProviderScope(
      overrides: <Override>[
        sessionSummaryRepositoryProvider.overrideWithValue(repo),
      ],
      child: MaterialApp.router(
        routerConfig: router,
        locale: locale,
        supportedLocales: AppL10n.supportedLocales,
        localizationsDelegates: const <LocalizationsDelegate<dynamic>>[
          ...AppL10n.localizationsDelegates,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
      ),
    ),
  );
  await tester.pumpAndSettle();
}

void main() {
  group('AiSummaryScreen (Page 034)', () {
    testWidgets('renders the summary sections + the AI banner', (tester) async {
      final repo = _FakeSummaryRepo(summary: _summary());
      await _pump(tester, repo: repo, sessionId: 's1');

      expect(repo.calls, 1);
      expect(find.text('Generated by AI'), findsOneWidget);
      expect(find.text('Coral cover rising'), findsOneWidget);
      expect(find.text('New survey method'), findsOneWidget);
      expect(find.text('Scale the reef programme'), findsOneWidget);
      expect(find.text('Dr Reef, Cmdr Tide'), findsOneWidget);
      expect(
        find.text('The session covered reef restoration progress.'),
        findsOneWidget,
      );
    });

    testWidgets('no sessionId shows the open-from-session empty state — no fetch',
        (tester) async {
      final repo = _FakeSummaryRepo(summary: _summary());
      await _pump(tester, repo: repo);

      expect(repo.calls, 0);
      expect(
        find.text('Open a session summary from a session.'),
        findsOneWidget,
      );
    });

    testWidgets('a blank sessionId is treated as no id', (tester) async {
      final repo = _FakeSummaryRepo(summary: _summary());
      await _pump(tester, repo: repo, sessionId: '   ');

      expect(repo.calls, 0);
      expect(
        find.text('Open a session summary from a session.'),
        findsOneWidget,
      );
    });

    testWidgets('a 404 shows the no-published-summary state', (tester) async {
      await _pump(
        tester,
        repo: _FakeSummaryRepo(status: 404),
        sessionId: 's1',
      );

      expect(find.text('No published summary yet.'), findsOneWidget);
    });

    testWidgets('a non-404 failure shows error + retry, which re-fetches',
        (tester) async {
      final repo = _FakeSummaryRepo(status: 500);
      await _pump(tester, repo: repo, sessionId: 's1');

      expect(find.text('Could not load the summary.'), findsOneWidget);
      await tester.tap(find.widgetWithText(FilledButton, 'Retry'));
      await tester.pumpAndSettle();
      expect(repo.calls, greaterThanOrEqualTo(2));
    });
  });
}
