// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUMVVbtnPUEabw1ixdPYQgAriE6TX8Hvc',
    appId: '1:956824410882:web:d636ef043c1f87d10fc01b',
    messagingSenderId: '956824410882',
    projectId: 'simfsa-c28ef',
    authDomain: 'simfsa-c28ef.firebaseapp.com',
    storageBucket: 'simfsa-c28ef.firebasestorage.app',
    measurementId: 'G-LY73H2PXMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUWJH4NAfC1R5ZZ3JShgL_wxQQy_zO3g4',
    appId: '1:956824410882:android:31a8a8d756a1de860fc01b',
    messagingSenderId: '956824410882',
    projectId: 'simfsa-c28ef',
    storageBucket: 'simfsa-c28ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeMrbLHRLooz3AgClncENHCUNBDx6Li0g',
    appId: '1:956824410882:ios:dc38697f3b531b6c0fc01b',
    messagingSenderId: '956824410882',
    projectId: 'simfsa-c28ef',
    storageBucket: 'simfsa-c28ef.firebasestorage.app',
    iosBundleId: 'com.simf.simfApp',
  );
}
